//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CT.ADIM.WEB.wsCorTurProd {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsCorTurProd.WSAdminSoap")]
    public interface WSAdminSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombre del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert_Circuito", ReplyAction="*")]
        CT.ADIM.WEB.wsCorTurProd.Insert_CircuitoResponse Insert_Circuito(CT.ADIM.WEB.wsCorTurProd.Insert_CircuitoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert_Circuito", ReplyAction="*")]
        System.Threading.Tasks.Task<CT.ADIM.WEB.wsCorTurProd.Insert_CircuitoResponse> Insert_CircuitoAsync(CT.ADIM.WEB.wsCorTurProd.Insert_CircuitoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento id_circuito del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update_Circuito", ReplyAction="*")]
        CT.ADIM.WEB.wsCorTurProd.Update_CircuitoResponse Update_Circuito(CT.ADIM.WEB.wsCorTurProd.Update_CircuitoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update_Circuito", ReplyAction="*")]
        System.Threading.Tasks.Task<CT.ADIM.WEB.wsCorTurProd.Update_CircuitoResponse> Update_CircuitoAsync(CT.ADIM.WEB.wsCorTurProd.Update_CircuitoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento latitud del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert_Sitio", ReplyAction="*")]
        CT.ADIM.WEB.wsCorTurProd.Insert_SitioResponse Insert_Sitio(CT.ADIM.WEB.wsCorTurProd.Insert_SitioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert_Sitio", ReplyAction="*")]
        System.Threading.Tasks.Task<CT.ADIM.WEB.wsCorTurProd.Insert_SitioResponse> Insert_SitioAsync(CT.ADIM.WEB.wsCorTurProd.Insert_SitioRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento id_sitio del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update_Sitio", ReplyAction="*")]
        CT.ADIM.WEB.wsCorTurProd.Update_SitioResponse Update_Sitio(CT.ADIM.WEB.wsCorTurProd.Update_SitioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update_Sitio", ReplyAction="*")]
        System.Threading.Tasks.Task<CT.ADIM.WEB.wsCorTurProd.Update_SitioResponse> Update_SitioAsync(CT.ADIM.WEB.wsCorTurProd.Update_SitioRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento url_imagen del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert_Imagen_Sitio", ReplyAction="*")]
        CT.ADIM.WEB.wsCorTurProd.Insert_Imagen_SitioResponse Insert_Imagen_Sitio(CT.ADIM.WEB.wsCorTurProd.Insert_Imagen_SitioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert_Imagen_Sitio", ReplyAction="*")]
        System.Threading.Tasks.Task<CT.ADIM.WEB.wsCorTurProd.Insert_Imagen_SitioResponse> Insert_Imagen_SitioAsync(CT.ADIM.WEB.wsCorTurProd.Insert_Imagen_SitioRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Update_Imagen_SitioResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update_Imagen_Sitio", ReplyAction="*")]
        CT.ADIM.WEB.wsCorTurProd.Update_Imagen_SitioResponse Update_Imagen_Sitio(CT.ADIM.WEB.wsCorTurProd.Update_Imagen_SitioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update_Imagen_Sitio", ReplyAction="*")]
        System.Threading.Tasks.Task<CT.ADIM.WEB.wsCorTurProd.Update_Imagen_SitioResponse> Update_Imagen_SitioAsync(CT.ADIM.WEB.wsCorTurProd.Update_Imagen_SitioRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Delete_CircuitoResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete_Circuito", ReplyAction="*")]
        CT.ADIM.WEB.wsCorTurProd.Delete_CircuitoResponse Delete_Circuito(CT.ADIM.WEB.wsCorTurProd.Delete_CircuitoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete_Circuito", ReplyAction="*")]
        System.Threading.Tasks.Task<CT.ADIM.WEB.wsCorTurProd.Delete_CircuitoResponse> Delete_CircuitoAsync(CT.ADIM.WEB.wsCorTurProd.Delete_CircuitoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Delete_SitioResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete_Sitio", ReplyAction="*")]
        CT.ADIM.WEB.wsCorTurProd.Delete_SitioResponse Delete_Sitio(CT.ADIM.WEB.wsCorTurProd.Delete_SitioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete_Sitio", ReplyAction="*")]
        System.Threading.Tasks.Task<CT.ADIM.WEB.wsCorTurProd.Delete_SitioResponse> Delete_SitioAsync(CT.ADIM.WEB.wsCorTurProd.Delete_SitioRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Delete_ImagenesResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete_Imagenes", ReplyAction="*")]
        CT.ADIM.WEB.wsCorTurProd.Delete_ImagenesResponse Delete_Imagenes(CT.ADIM.WEB.wsCorTurProd.Delete_ImagenesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete_Imagenes", ReplyAction="*")]
        System.Threading.Tasks.Task<CT.ADIM.WEB.wsCorTurProd.Delete_ImagenesResponse> Delete_ImagenesAsync(CT.ADIM.WEB.wsCorTurProd.Delete_ImagenesRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Update_Info_WebResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update_Info_Web", ReplyAction="*")]
        CT.ADIM.WEB.wsCorTurProd.Update_Info_WebResponse Update_Info_Web(CT.ADIM.WEB.wsCorTurProd.Update_Info_WebRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update_Info_Web", ReplyAction="*")]
        System.Threading.Tasks.Task<CT.ADIM.WEB.wsCorTurProd.Update_Info_WebResponse> Update_Info_WebAsync(CT.ADIM.WEB.wsCorTurProd.Update_Info_WebRequest request);
        

        // CODEGEN: Generating message contract since element name nombres_usuario from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert_Usuario_Guia", ReplyAction="*")]
        CT.ADIM.WEB.wsCorTurProd.Insert_Usuario_GuiaResponse Insert_Usuario_Guia(CT.ADIM.WEB.wsCorTurProd.Insert_Usuario_GuiaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert_Usuario_Guia", ReplyAction="*")]
        System.Threading.Tasks.Task<CT.ADIM.WEB.wsCorTurProd.Insert_Usuario_GuiaResponse> Insert_Usuario_GuiaAsync(CT.ADIM.WEB.wsCorTurProd.Insert_Usuario_GuiaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TextSpeak", ReplyAction="*")]
        void TextSpeak();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TextSpeak", ReplyAction="*")]
        System.Threading.Tasks.Task TextSpeakAsync();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Insert_CircuitoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Insert_Circuito", Namespace="http://tempuri.org/", Order=0)]
        public CT.ADIM.WEB.wsCorTurProd.Insert_CircuitoRequestBody Body;
        
        public Insert_CircuitoRequest() {
        }
        
        public Insert_CircuitoRequest(CT.ADIM.WEB.wsCorTurProd.Insert_CircuitoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Insert_CircuitoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string descripcion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string recomendaciones;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string equipamento;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string edad;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string horario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string tiempo_estimado;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string codigo_idioma;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public int fk_categoria;
        
        public Insert_CircuitoRequestBody() {
        }
        
        public Insert_CircuitoRequestBody(string nombre, string descripcion, string recomendaciones, string equipamento, string edad, string horario, string tiempo_estimado, string codigo_idioma, int fk_categoria) {
            this.nombre = nombre;
            this.descripcion = descripcion;
            this.recomendaciones = recomendaciones;
            this.equipamento = equipamento;
            this.edad = edad;
            this.horario = horario;
            this.tiempo_estimado = tiempo_estimado;
            this.codigo_idioma = codigo_idioma;
            this.fk_categoria = fk_categoria;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Insert_CircuitoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Insert_CircuitoResponse", Namespace="http://tempuri.org/", Order=0)]
        public CT.ADIM.WEB.wsCorTurProd.Insert_CircuitoResponseBody Body;
        
        public Insert_CircuitoResponse() {
        }
        
        public Insert_CircuitoResponse(CT.ADIM.WEB.wsCorTurProd.Insert_CircuitoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Insert_CircuitoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Insert_CircuitoResult;
        
        public Insert_CircuitoResponseBody() {
        }
        
        public Insert_CircuitoResponseBody(string Insert_CircuitoResult) {
            this.Insert_CircuitoResult = Insert_CircuitoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Update_CircuitoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Update_Circuito", Namespace="http://tempuri.org/", Order=0)]
        public CT.ADIM.WEB.wsCorTurProd.Update_CircuitoRequestBody Body;
        
        public Update_CircuitoRequest() {
        }
        
        public Update_CircuitoRequest(CT.ADIM.WEB.wsCorTurProd.Update_CircuitoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Update_CircuitoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id_circuito;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string descripcion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string recomendaciones;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string equipamento;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string edad;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string horario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string tiempo_estimado;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string codigo_idioma;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public int fk_categoria;
        
        public Update_CircuitoRequestBody() {
        }
        
        public Update_CircuitoRequestBody(string id_circuito, string nombre, string descripcion, string recomendaciones, string equipamento, string edad, string horario, string tiempo_estimado, string codigo_idioma, int fk_categoria) {
            this.id_circuito = id_circuito;
            this.nombre = nombre;
            this.descripcion = descripcion;
            this.recomendaciones = recomendaciones;
            this.equipamento = equipamento;
            this.edad = edad;
            this.horario = horario;
            this.tiempo_estimado = tiempo_estimado;
            this.codigo_idioma = codigo_idioma;
            this.fk_categoria = fk_categoria;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Update_CircuitoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Update_CircuitoResponse", Namespace="http://tempuri.org/", Order=0)]
        public CT.ADIM.WEB.wsCorTurProd.Update_CircuitoResponseBody Body;
        
        public Update_CircuitoResponse() {
        }
        
        public Update_CircuitoResponse(CT.ADIM.WEB.wsCorTurProd.Update_CircuitoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Update_CircuitoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Update_CircuitoResult;
        
        public Update_CircuitoResponseBody() {
        }
        
        public Update_CircuitoResponseBody(string Update_CircuitoResult) {
            this.Update_CircuitoResult = Update_CircuitoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Insert_SitioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Insert_Sitio", Namespace="http://tempuri.org/", Order=0)]
        public CT.ADIM.WEB.wsCorTurProd.Insert_SitioRequestBody Body;
        
        public Insert_SitioRequest() {
        }
        
        public Insert_SitioRequest(CT.ADIM.WEB.wsCorTurProd.Insert_SitioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Insert_SitioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string latitud;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string longitud;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string direccion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string costo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ciudad;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string pais;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string descripcion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string equipamento;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string recomendaciones;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string tiempo_estimado;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string edad;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string horario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string codigo_idioma;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string telefono_sitio;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string ira;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=16)]
        public int id_circuito;
        
        public Insert_SitioRequestBody() {
        }
        
        public Insert_SitioRequestBody(
                    string latitud, 
                    string longitud, 
                    string direccion, 
                    string costo, 
                    string ciudad, 
                    string pais, 
                    string nombre, 
                    string descripcion, 
                    string equipamento, 
                    string recomendaciones, 
                    string tiempo_estimado, 
                    string edad, 
                    string horario, 
                    string codigo_idioma, 
                    string telefono_sitio, 
                    string ira, 
                    int id_circuito) {
            this.latitud = latitud;
            this.longitud = longitud;
            this.direccion = direccion;
            this.costo = costo;
            this.ciudad = ciudad;
            this.pais = pais;
            this.nombre = nombre;
            this.descripcion = descripcion;
            this.equipamento = equipamento;
            this.recomendaciones = recomendaciones;
            this.tiempo_estimado = tiempo_estimado;
            this.edad = edad;
            this.horario = horario;
            this.codigo_idioma = codigo_idioma;
            this.telefono_sitio = telefono_sitio;
            this.ira = ira;
            this.id_circuito = id_circuito;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Insert_SitioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Insert_SitioResponse", Namespace="http://tempuri.org/", Order=0)]
        public CT.ADIM.WEB.wsCorTurProd.Insert_SitioResponseBody Body;
        
        public Insert_SitioResponse() {
        }
        
        public Insert_SitioResponse(CT.ADIM.WEB.wsCorTurProd.Insert_SitioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Insert_SitioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Insert_SitioResult;
        
        public Insert_SitioResponseBody() {
        }
        
        public Insert_SitioResponseBody(string Insert_SitioResult) {
            this.Insert_SitioResult = Insert_SitioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Update_SitioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Update_Sitio", Namespace="http://tempuri.org/", Order=0)]
        public CT.ADIM.WEB.wsCorTurProd.Update_SitioRequestBody Body;
        
        public Update_SitioRequest() {
        }
        
        public Update_SitioRequest(CT.ADIM.WEB.wsCorTurProd.Update_SitioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Update_SitioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id_sitio;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string latitud;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string longitud;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string direccion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string costo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string ciudad;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string pais;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string descripcion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string equipamento;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string recomendaciones;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string tiempo_estimado;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string edad;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string horario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string ira;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string codigo_idioma;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string telefono_sitio;
        
        public Update_SitioRequestBody() {
        }
        
        public Update_SitioRequestBody(
                    string id_sitio, 
                    string latitud, 
                    string longitud, 
                    string direccion, 
                    string costo, 
                    string ciudad, 
                    string pais, 
                    string nombre, 
                    string descripcion, 
                    string equipamento, 
                    string recomendaciones, 
                    string tiempo_estimado, 
                    string edad, 
                    string horario, 
                    string ira, 
                    string codigo_idioma, 
                    string telefono_sitio) {
            this.id_sitio = id_sitio;
            this.latitud = latitud;
            this.longitud = longitud;
            this.direccion = direccion;
            this.costo = costo;
            this.ciudad = ciudad;
            this.pais = pais;
            this.nombre = nombre;
            this.descripcion = descripcion;
            this.equipamento = equipamento;
            this.recomendaciones = recomendaciones;
            this.tiempo_estimado = tiempo_estimado;
            this.edad = edad;
            this.horario = horario;
            this.ira = ira;
            this.codigo_idioma = codigo_idioma;
            this.telefono_sitio = telefono_sitio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Update_SitioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Update_SitioResponse", Namespace="http://tempuri.org/", Order=0)]
        public CT.ADIM.WEB.wsCorTurProd.Update_SitioResponseBody Body;
        
        public Update_SitioResponse() {
        }
        
        public Update_SitioResponse(CT.ADIM.WEB.wsCorTurProd.Update_SitioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Update_SitioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Update_SitioResult;
        
        public Update_SitioResponseBody() {
        }
        
        public Update_SitioResponseBody(string Update_SitioResult) {
            this.Update_SitioResult = Update_SitioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Insert_Imagen_SitioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Insert_Imagen_Sitio", Namespace="http://tempuri.org/", Order=0)]
        public CT.ADIM.WEB.wsCorTurProd.Insert_Imagen_SitioRequestBody Body;
        
        public Insert_Imagen_SitioRequest() {
        }
        
        public Insert_Imagen_SitioRequest(CT.ADIM.WEB.wsCorTurProd.Insert_Imagen_SitioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Insert_Imagen_SitioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string url_imagen;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int fk_sitio;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int orden;
        
        public Insert_Imagen_SitioRequestBody() {
        }
        
        public Insert_Imagen_SitioRequestBody(string url_imagen, int fk_sitio, int orden) {
            this.url_imagen = url_imagen;
            this.fk_sitio = fk_sitio;
            this.orden = orden;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Insert_Imagen_SitioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Insert_Imagen_SitioResponse", Namespace="http://tempuri.org/", Order=0)]
        public CT.ADIM.WEB.wsCorTurProd.Insert_Imagen_SitioResponseBody Body;
        
        public Insert_Imagen_SitioResponse() {
        }
        
        public Insert_Imagen_SitioResponse(CT.ADIM.WEB.wsCorTurProd.Insert_Imagen_SitioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Insert_Imagen_SitioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Insert_Imagen_SitioResult;
        
        public Insert_Imagen_SitioResponseBody() {
        }
        
        public Insert_Imagen_SitioResponseBody(string Insert_Imagen_SitioResult) {
            this.Insert_Imagen_SitioResult = Insert_Imagen_SitioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Update_Imagen_SitioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Update_Imagen_Sitio", Namespace="http://tempuri.org/", Order=0)]
        public CT.ADIM.WEB.wsCorTurProd.Update_Imagen_SitioRequestBody Body;
        
        public Update_Imagen_SitioRequest() {
        }
        
        public Update_Imagen_SitioRequest(CT.ADIM.WEB.wsCorTurProd.Update_Imagen_SitioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Update_Imagen_SitioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id_imagen;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int orden;
        
        public Update_Imagen_SitioRequestBody() {
        }
        
        public Update_Imagen_SitioRequestBody(int id_imagen, int orden) {
            this.id_imagen = id_imagen;
            this.orden = orden;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Update_Imagen_SitioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Update_Imagen_SitioResponse", Namespace="http://tempuri.org/", Order=0)]
        public CT.ADIM.WEB.wsCorTurProd.Update_Imagen_SitioResponseBody Body;
        
        public Update_Imagen_SitioResponse() {
        }
        
        public Update_Imagen_SitioResponse(CT.ADIM.WEB.wsCorTurProd.Update_Imagen_SitioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Update_Imagen_SitioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Update_Imagen_SitioResult;
        
        public Update_Imagen_SitioResponseBody() {
        }
        
        public Update_Imagen_SitioResponseBody(string Update_Imagen_SitioResult) {
            this.Update_Imagen_SitioResult = Update_Imagen_SitioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Delete_CircuitoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Delete_Circuito", Namespace="http://tempuri.org/", Order=0)]
        public CT.ADIM.WEB.wsCorTurProd.Delete_CircuitoRequestBody Body;
        
        public Delete_CircuitoRequest() {
        }
        
        public Delete_CircuitoRequest(CT.ADIM.WEB.wsCorTurProd.Delete_CircuitoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Delete_CircuitoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id_circuito;
        
        public Delete_CircuitoRequestBody() {
        }
        
        public Delete_CircuitoRequestBody(int id_circuito) {
            this.id_circuito = id_circuito;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Delete_CircuitoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Delete_CircuitoResponse", Namespace="http://tempuri.org/", Order=0)]
        public CT.ADIM.WEB.wsCorTurProd.Delete_CircuitoResponseBody Body;
        
        public Delete_CircuitoResponse() {
        }
        
        public Delete_CircuitoResponse(CT.ADIM.WEB.wsCorTurProd.Delete_CircuitoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Delete_CircuitoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Delete_CircuitoResult;
        
        public Delete_CircuitoResponseBody() {
        }
        
        public Delete_CircuitoResponseBody(string Delete_CircuitoResult) {
            this.Delete_CircuitoResult = Delete_CircuitoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Delete_SitioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Delete_Sitio", Namespace="http://tempuri.org/", Order=0)]
        public CT.ADIM.WEB.wsCorTurProd.Delete_SitioRequestBody Body;
        
        public Delete_SitioRequest() {
        }
        
        public Delete_SitioRequest(CT.ADIM.WEB.wsCorTurProd.Delete_SitioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Delete_SitioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id_sitio;
        
        public Delete_SitioRequestBody() {
        }
        
        public Delete_SitioRequestBody(int id_sitio) {
            this.id_sitio = id_sitio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Delete_SitioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Delete_SitioResponse", Namespace="http://tempuri.org/", Order=0)]
        public CT.ADIM.WEB.wsCorTurProd.Delete_SitioResponseBody Body;
        
        public Delete_SitioResponse() {
        }
        
        public Delete_SitioResponse(CT.ADIM.WEB.wsCorTurProd.Delete_SitioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Delete_SitioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Delete_SitioResult;
        
        public Delete_SitioResponseBody() {
        }
        
        public Delete_SitioResponseBody(string Delete_SitioResult) {
            this.Delete_SitioResult = Delete_SitioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Delete_ImagenesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Delete_Imagenes", Namespace="http://tempuri.org/", Order=0)]
        public CT.ADIM.WEB.wsCorTurProd.Delete_ImagenesRequestBody Body;
        
        public Delete_ImagenesRequest() {
        }
        
        public Delete_ImagenesRequest(CT.ADIM.WEB.wsCorTurProd.Delete_ImagenesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Delete_ImagenesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id_imagen;
        
        public Delete_ImagenesRequestBody() {
        }
        
        public Delete_ImagenesRequestBody(int id_imagen) {
            this.id_imagen = id_imagen;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Delete_ImagenesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Delete_ImagenesResponse", Namespace="http://tempuri.org/", Order=0)]
        public CT.ADIM.WEB.wsCorTurProd.Delete_ImagenesResponseBody Body;
        
        public Delete_ImagenesResponse() {
        }
        
        public Delete_ImagenesResponse(CT.ADIM.WEB.wsCorTurProd.Delete_ImagenesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Delete_ImagenesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Delete_ImagenesResult;
        
        public Delete_ImagenesResponseBody() {
        }
        
        public Delete_ImagenesResponseBody(string Delete_ImagenesResult) {
            this.Delete_ImagenesResult = Delete_ImagenesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Update_Info_WebRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Update_Info_Web", Namespace="http://tempuri.org/", Order=0)]
        public CT.ADIM.WEB.wsCorTurProd.Update_Info_WebRequestBody Body;
        
        public Update_Info_WebRequest() {
        }
        
        public Update_Info_WebRequest(CT.ADIM.WEB.wsCorTurProd.Update_Info_WebRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class Update_Info_WebRequestBody {
        
        public Update_Info_WebRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Update_Info_WebResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Update_Info_WebResponse", Namespace="http://tempuri.org/", Order=0)]
        public CT.ADIM.WEB.wsCorTurProd.Update_Info_WebResponseBody Body;
        
        public Update_Info_WebResponse() {
        }
        
        public Update_Info_WebResponse(CT.ADIM.WEB.wsCorTurProd.Update_Info_WebResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Update_Info_WebResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Update_Info_WebResult;
        
        public Update_Info_WebResponseBody() {
        }
        
        public Update_Info_WebResponseBody(string Update_Info_WebResult) {
            this.Update_Info_WebResult = Update_Info_WebResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Insert_Usuario_GuiaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Insert_Usuario_Guia", Namespace="http://tempuri.org/", Order=0)]
        public CT.ADIM.WEB.wsCorTurProd.Insert_Usuario_GuiaRequestBody Body;
        
        public Insert_Usuario_GuiaRequest() {
        }
        
        public Insert_Usuario_GuiaRequest(CT.ADIM.WEB.wsCorTurProd.Insert_Usuario_GuiaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Insert_Usuario_GuiaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombres_usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string apellidos_usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string correo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string contrasena;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int numero_certificado;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Vigencia_Certificado;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int ciudad;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public byte foto;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public byte foto_certificado;
        
        public Insert_Usuario_GuiaRequestBody() {
        }
        
        public Insert_Usuario_GuiaRequestBody(string nombres_usuario, string apellidos_usuario, string correo, string usuario, string contrasena, int numero_certificado, string Vigencia_Certificado, int ciudad, byte foto, byte foto_certificado) {
            this.nombres_usuario = nombres_usuario;
            this.apellidos_usuario = apellidos_usuario;
            this.correo = correo;
            this.usuario = usuario;
            this.contrasena = contrasena;
            this.numero_certificado = numero_certificado;
            this.Vigencia_Certificado = Vigencia_Certificado;
            this.ciudad = ciudad;
            this.foto = foto;
            this.foto_certificado = foto_certificado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Insert_Usuario_GuiaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Insert_Usuario_GuiaResponse", Namespace="http://tempuri.org/", Order=0)]
        public CT.ADIM.WEB.wsCorTurProd.Insert_Usuario_GuiaResponseBody Body;
        
        public Insert_Usuario_GuiaResponse() {
        }
        
        public Insert_Usuario_GuiaResponse(CT.ADIM.WEB.wsCorTurProd.Insert_Usuario_GuiaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Insert_Usuario_GuiaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Insert_Usuario_GuiaResult;
        
        public Insert_Usuario_GuiaResponseBody() {
        }
        
        public Insert_Usuario_GuiaResponseBody(string Insert_Usuario_GuiaResult) {
            this.Insert_Usuario_GuiaResult = Insert_Usuario_GuiaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSAdminSoapChannel : CT.ADIM.WEB.wsCorTurProd.WSAdminSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSAdminSoapClient : System.ServiceModel.ClientBase<CT.ADIM.WEB.wsCorTurProd.WSAdminSoap>, CT.ADIM.WEB.wsCorTurProd.WSAdminSoap {
        
        public WSAdminSoapClient() {
        }
        
        public WSAdminSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSAdminSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSAdminSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSAdminSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CT.ADIM.WEB.wsCorTurProd.Insert_CircuitoResponse CT.ADIM.WEB.wsCorTurProd.WSAdminSoap.Insert_Circuito(CT.ADIM.WEB.wsCorTurProd.Insert_CircuitoRequest request) {
            return base.Channel.Insert_Circuito(request);
        }
        
        public string Insert_Circuito(string nombre, string descripcion, string recomendaciones, string equipamento, string edad, string horario, string tiempo_estimado, string codigo_idioma, int fk_categoria) {
            CT.ADIM.WEB.wsCorTurProd.Insert_CircuitoRequest inValue = new CT.ADIM.WEB.wsCorTurProd.Insert_CircuitoRequest();
            inValue.Body = new CT.ADIM.WEB.wsCorTurProd.Insert_CircuitoRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.descripcion = descripcion;
            inValue.Body.recomendaciones = recomendaciones;
            inValue.Body.equipamento = equipamento;
            inValue.Body.edad = edad;
            inValue.Body.horario = horario;
            inValue.Body.tiempo_estimado = tiempo_estimado;
            inValue.Body.codigo_idioma = codigo_idioma;
            inValue.Body.fk_categoria = fk_categoria;
            CT.ADIM.WEB.wsCorTurProd.Insert_CircuitoResponse retVal = ((CT.ADIM.WEB.wsCorTurProd.WSAdminSoap)(this)).Insert_Circuito(inValue);
            return retVal.Body.Insert_CircuitoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CT.ADIM.WEB.wsCorTurProd.Insert_CircuitoResponse> CT.ADIM.WEB.wsCorTurProd.WSAdminSoap.Insert_CircuitoAsync(CT.ADIM.WEB.wsCorTurProd.Insert_CircuitoRequest request) {
            return base.Channel.Insert_CircuitoAsync(request);
        }
        
        public System.Threading.Tasks.Task<CT.ADIM.WEB.wsCorTurProd.Insert_CircuitoResponse> Insert_CircuitoAsync(string nombre, string descripcion, string recomendaciones, string equipamento, string edad, string horario, string tiempo_estimado, string codigo_idioma, int fk_categoria) {
            CT.ADIM.WEB.wsCorTurProd.Insert_CircuitoRequest inValue = new CT.ADIM.WEB.wsCorTurProd.Insert_CircuitoRequest();
            inValue.Body = new CT.ADIM.WEB.wsCorTurProd.Insert_CircuitoRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.descripcion = descripcion;
            inValue.Body.recomendaciones = recomendaciones;
            inValue.Body.equipamento = equipamento;
            inValue.Body.edad = edad;
            inValue.Body.horario = horario;
            inValue.Body.tiempo_estimado = tiempo_estimado;
            inValue.Body.codigo_idioma = codigo_idioma;
            inValue.Body.fk_categoria = fk_categoria;
            return ((CT.ADIM.WEB.wsCorTurProd.WSAdminSoap)(this)).Insert_CircuitoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CT.ADIM.WEB.wsCorTurProd.Update_CircuitoResponse CT.ADIM.WEB.wsCorTurProd.WSAdminSoap.Update_Circuito(CT.ADIM.WEB.wsCorTurProd.Update_CircuitoRequest request) {
            return base.Channel.Update_Circuito(request);
        }
        
        public string Update_Circuito(string id_circuito, string nombre, string descripcion, string recomendaciones, string equipamento, string edad, string horario, string tiempo_estimado, string codigo_idioma, int fk_categoria) {
            CT.ADIM.WEB.wsCorTurProd.Update_CircuitoRequest inValue = new CT.ADIM.WEB.wsCorTurProd.Update_CircuitoRequest();
            inValue.Body = new CT.ADIM.WEB.wsCorTurProd.Update_CircuitoRequestBody();
            inValue.Body.id_circuito = id_circuito;
            inValue.Body.nombre = nombre;
            inValue.Body.descripcion = descripcion;
            inValue.Body.recomendaciones = recomendaciones;
            inValue.Body.equipamento = equipamento;
            inValue.Body.edad = edad;
            inValue.Body.horario = horario;
            inValue.Body.tiempo_estimado = tiempo_estimado;
            inValue.Body.codigo_idioma = codigo_idioma;
            inValue.Body.fk_categoria = fk_categoria;
            CT.ADIM.WEB.wsCorTurProd.Update_CircuitoResponse retVal = ((CT.ADIM.WEB.wsCorTurProd.WSAdminSoap)(this)).Update_Circuito(inValue);
            return retVal.Body.Update_CircuitoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CT.ADIM.WEB.wsCorTurProd.Update_CircuitoResponse> CT.ADIM.WEB.wsCorTurProd.WSAdminSoap.Update_CircuitoAsync(CT.ADIM.WEB.wsCorTurProd.Update_CircuitoRequest request) {
            return base.Channel.Update_CircuitoAsync(request);
        }
        
        public System.Threading.Tasks.Task<CT.ADIM.WEB.wsCorTurProd.Update_CircuitoResponse> Update_CircuitoAsync(string id_circuito, string nombre, string descripcion, string recomendaciones, string equipamento, string edad, string horario, string tiempo_estimado, string codigo_idioma, int fk_categoria) {
            CT.ADIM.WEB.wsCorTurProd.Update_CircuitoRequest inValue = new CT.ADIM.WEB.wsCorTurProd.Update_CircuitoRequest();
            inValue.Body = new CT.ADIM.WEB.wsCorTurProd.Update_CircuitoRequestBody();
            inValue.Body.id_circuito = id_circuito;
            inValue.Body.nombre = nombre;
            inValue.Body.descripcion = descripcion;
            inValue.Body.recomendaciones = recomendaciones;
            inValue.Body.equipamento = equipamento;
            inValue.Body.edad = edad;
            inValue.Body.horario = horario;
            inValue.Body.tiempo_estimado = tiempo_estimado;
            inValue.Body.codigo_idioma = codigo_idioma;
            inValue.Body.fk_categoria = fk_categoria;
            return ((CT.ADIM.WEB.wsCorTurProd.WSAdminSoap)(this)).Update_CircuitoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CT.ADIM.WEB.wsCorTurProd.Insert_SitioResponse CT.ADIM.WEB.wsCorTurProd.WSAdminSoap.Insert_Sitio(CT.ADIM.WEB.wsCorTurProd.Insert_SitioRequest request) {
            return base.Channel.Insert_Sitio(request);
        }
        
        public string Insert_Sitio(
                    string latitud, 
                    string longitud, 
                    string direccion, 
                    string costo, 
                    string ciudad, 
                    string pais, 
                    string nombre, 
                    string descripcion, 
                    string equipamento, 
                    string recomendaciones, 
                    string tiempo_estimado, 
                    string edad, 
                    string horario, 
                    string codigo_idioma, 
                    string telefono_sitio, 
                    string ira, 
                    int id_circuito) {
            CT.ADIM.WEB.wsCorTurProd.Insert_SitioRequest inValue = new CT.ADIM.WEB.wsCorTurProd.Insert_SitioRequest();
            inValue.Body = new CT.ADIM.WEB.wsCorTurProd.Insert_SitioRequestBody();
            inValue.Body.latitud = latitud;
            inValue.Body.longitud = longitud;
            inValue.Body.direccion = direccion;
            inValue.Body.costo = costo;
            inValue.Body.ciudad = ciudad;
            inValue.Body.pais = pais;
            inValue.Body.nombre = nombre;
            inValue.Body.descripcion = descripcion;
            inValue.Body.equipamento = equipamento;
            inValue.Body.recomendaciones = recomendaciones;
            inValue.Body.tiempo_estimado = tiempo_estimado;
            inValue.Body.edad = edad;
            inValue.Body.horario = horario;
            inValue.Body.codigo_idioma = codigo_idioma;
            inValue.Body.telefono_sitio = telefono_sitio;
            inValue.Body.ira = ira;
            inValue.Body.id_circuito = id_circuito;
            CT.ADIM.WEB.wsCorTurProd.Insert_SitioResponse retVal = ((CT.ADIM.WEB.wsCorTurProd.WSAdminSoap)(this)).Insert_Sitio(inValue);
            return retVal.Body.Insert_SitioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CT.ADIM.WEB.wsCorTurProd.Insert_SitioResponse> CT.ADIM.WEB.wsCorTurProd.WSAdminSoap.Insert_SitioAsync(CT.ADIM.WEB.wsCorTurProd.Insert_SitioRequest request) {
            return base.Channel.Insert_SitioAsync(request);
        }
        
        public System.Threading.Tasks.Task<CT.ADIM.WEB.wsCorTurProd.Insert_SitioResponse> Insert_SitioAsync(
                    string latitud, 
                    string longitud, 
                    string direccion, 
                    string costo, 
                    string ciudad, 
                    string pais, 
                    string nombre, 
                    string descripcion, 
                    string equipamento, 
                    string recomendaciones, 
                    string tiempo_estimado, 
                    string edad, 
                    string horario, 
                    string codigo_idioma, 
                    string telefono_sitio, 
                    string ira, 
                    int id_circuito) {
            CT.ADIM.WEB.wsCorTurProd.Insert_SitioRequest inValue = new CT.ADIM.WEB.wsCorTurProd.Insert_SitioRequest();
            inValue.Body = new CT.ADIM.WEB.wsCorTurProd.Insert_SitioRequestBody();
            inValue.Body.latitud = latitud;
            inValue.Body.longitud = longitud;
            inValue.Body.direccion = direccion;
            inValue.Body.costo = costo;
            inValue.Body.ciudad = ciudad;
            inValue.Body.pais = pais;
            inValue.Body.nombre = nombre;
            inValue.Body.descripcion = descripcion;
            inValue.Body.equipamento = equipamento;
            inValue.Body.recomendaciones = recomendaciones;
            inValue.Body.tiempo_estimado = tiempo_estimado;
            inValue.Body.edad = edad;
            inValue.Body.horario = horario;
            inValue.Body.codigo_idioma = codigo_idioma;
            inValue.Body.telefono_sitio = telefono_sitio;
            inValue.Body.ira = ira;
            inValue.Body.id_circuito = id_circuito;
            return ((CT.ADIM.WEB.wsCorTurProd.WSAdminSoap)(this)).Insert_SitioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CT.ADIM.WEB.wsCorTurProd.Update_SitioResponse CT.ADIM.WEB.wsCorTurProd.WSAdminSoap.Update_Sitio(CT.ADIM.WEB.wsCorTurProd.Update_SitioRequest request) {
            return base.Channel.Update_Sitio(request);
        }
        
        public string Update_Sitio(
                    string id_sitio, 
                    string latitud, 
                    string longitud, 
                    string direccion, 
                    string costo, 
                    string ciudad, 
                    string pais, 
                    string nombre, 
                    string descripcion, 
                    string equipamento, 
                    string recomendaciones, 
                    string tiempo_estimado, 
                    string edad, 
                    string horario, 
                    string ira, 
                    string codigo_idioma, 
                    string telefono_sitio) {
            CT.ADIM.WEB.wsCorTurProd.Update_SitioRequest inValue = new CT.ADIM.WEB.wsCorTurProd.Update_SitioRequest();
            inValue.Body = new CT.ADIM.WEB.wsCorTurProd.Update_SitioRequestBody();
            inValue.Body.id_sitio = id_sitio;
            inValue.Body.latitud = latitud;
            inValue.Body.longitud = longitud;
            inValue.Body.direccion = direccion;
            inValue.Body.costo = costo;
            inValue.Body.ciudad = ciudad;
            inValue.Body.pais = pais;
            inValue.Body.nombre = nombre;
            inValue.Body.descripcion = descripcion;
            inValue.Body.equipamento = equipamento;
            inValue.Body.recomendaciones = recomendaciones;
            inValue.Body.tiempo_estimado = tiempo_estimado;
            inValue.Body.edad = edad;
            inValue.Body.horario = horario;
            inValue.Body.ira = ira;
            inValue.Body.codigo_idioma = codigo_idioma;
            inValue.Body.telefono_sitio = telefono_sitio;
            CT.ADIM.WEB.wsCorTurProd.Update_SitioResponse retVal = ((CT.ADIM.WEB.wsCorTurProd.WSAdminSoap)(this)).Update_Sitio(inValue);
            return retVal.Body.Update_SitioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CT.ADIM.WEB.wsCorTurProd.Update_SitioResponse> CT.ADIM.WEB.wsCorTurProd.WSAdminSoap.Update_SitioAsync(CT.ADIM.WEB.wsCorTurProd.Update_SitioRequest request) {
            return base.Channel.Update_SitioAsync(request);
        }
        
        public System.Threading.Tasks.Task<CT.ADIM.WEB.wsCorTurProd.Update_SitioResponse> Update_SitioAsync(
                    string id_sitio, 
                    string latitud, 
                    string longitud, 
                    string direccion, 
                    string costo, 
                    string ciudad, 
                    string pais, 
                    string nombre, 
                    string descripcion, 
                    string equipamento, 
                    string recomendaciones, 
                    string tiempo_estimado, 
                    string edad, 
                    string horario, 
                    string ira, 
                    string codigo_idioma, 
                    string telefono_sitio) {
            CT.ADIM.WEB.wsCorTurProd.Update_SitioRequest inValue = new CT.ADIM.WEB.wsCorTurProd.Update_SitioRequest();
            inValue.Body = new CT.ADIM.WEB.wsCorTurProd.Update_SitioRequestBody();
            inValue.Body.id_sitio = id_sitio;
            inValue.Body.latitud = latitud;
            inValue.Body.longitud = longitud;
            inValue.Body.direccion = direccion;
            inValue.Body.costo = costo;
            inValue.Body.ciudad = ciudad;
            inValue.Body.pais = pais;
            inValue.Body.nombre = nombre;
            inValue.Body.descripcion = descripcion;
            inValue.Body.equipamento = equipamento;
            inValue.Body.recomendaciones = recomendaciones;
            inValue.Body.tiempo_estimado = tiempo_estimado;
            inValue.Body.edad = edad;
            inValue.Body.horario = horario;
            inValue.Body.ira = ira;
            inValue.Body.codigo_idioma = codigo_idioma;
            inValue.Body.telefono_sitio = telefono_sitio;
            return ((CT.ADIM.WEB.wsCorTurProd.WSAdminSoap)(this)).Update_SitioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CT.ADIM.WEB.wsCorTurProd.Insert_Imagen_SitioResponse CT.ADIM.WEB.wsCorTurProd.WSAdminSoap.Insert_Imagen_Sitio(CT.ADIM.WEB.wsCorTurProd.Insert_Imagen_SitioRequest request) {
            return base.Channel.Insert_Imagen_Sitio(request);
        }
        
        public string Insert_Imagen_Sitio(string url_imagen, int fk_sitio, int orden) {
            CT.ADIM.WEB.wsCorTurProd.Insert_Imagen_SitioRequest inValue = new CT.ADIM.WEB.wsCorTurProd.Insert_Imagen_SitioRequest();
            inValue.Body = new CT.ADIM.WEB.wsCorTurProd.Insert_Imagen_SitioRequestBody();
            inValue.Body.url_imagen = url_imagen;
            inValue.Body.fk_sitio = fk_sitio;
            inValue.Body.orden = orden;
            CT.ADIM.WEB.wsCorTurProd.Insert_Imagen_SitioResponse retVal = ((CT.ADIM.WEB.wsCorTurProd.WSAdminSoap)(this)).Insert_Imagen_Sitio(inValue);
            return retVal.Body.Insert_Imagen_SitioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CT.ADIM.WEB.wsCorTurProd.Insert_Imagen_SitioResponse> CT.ADIM.WEB.wsCorTurProd.WSAdminSoap.Insert_Imagen_SitioAsync(CT.ADIM.WEB.wsCorTurProd.Insert_Imagen_SitioRequest request) {
            return base.Channel.Insert_Imagen_SitioAsync(request);
        }
        
        public System.Threading.Tasks.Task<CT.ADIM.WEB.wsCorTurProd.Insert_Imagen_SitioResponse> Insert_Imagen_SitioAsync(string url_imagen, int fk_sitio, int orden) {
            CT.ADIM.WEB.wsCorTurProd.Insert_Imagen_SitioRequest inValue = new CT.ADIM.WEB.wsCorTurProd.Insert_Imagen_SitioRequest();
            inValue.Body = new CT.ADIM.WEB.wsCorTurProd.Insert_Imagen_SitioRequestBody();
            inValue.Body.url_imagen = url_imagen;
            inValue.Body.fk_sitio = fk_sitio;
            inValue.Body.orden = orden;
            return ((CT.ADIM.WEB.wsCorTurProd.WSAdminSoap)(this)).Insert_Imagen_SitioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CT.ADIM.WEB.wsCorTurProd.Update_Imagen_SitioResponse CT.ADIM.WEB.wsCorTurProd.WSAdminSoap.Update_Imagen_Sitio(CT.ADIM.WEB.wsCorTurProd.Update_Imagen_SitioRequest request) {
            return base.Channel.Update_Imagen_Sitio(request);
        }
        
        public string Update_Imagen_Sitio(int id_imagen, int orden) {
            CT.ADIM.WEB.wsCorTurProd.Update_Imagen_SitioRequest inValue = new CT.ADIM.WEB.wsCorTurProd.Update_Imagen_SitioRequest();
            inValue.Body = new CT.ADIM.WEB.wsCorTurProd.Update_Imagen_SitioRequestBody();
            inValue.Body.id_imagen = id_imagen;
            inValue.Body.orden = orden;
            CT.ADIM.WEB.wsCorTurProd.Update_Imagen_SitioResponse retVal = ((CT.ADIM.WEB.wsCorTurProd.WSAdminSoap)(this)).Update_Imagen_Sitio(inValue);
            return retVal.Body.Update_Imagen_SitioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CT.ADIM.WEB.wsCorTurProd.Update_Imagen_SitioResponse> CT.ADIM.WEB.wsCorTurProd.WSAdminSoap.Update_Imagen_SitioAsync(CT.ADIM.WEB.wsCorTurProd.Update_Imagen_SitioRequest request) {
            return base.Channel.Update_Imagen_SitioAsync(request);
        }
        
        public System.Threading.Tasks.Task<CT.ADIM.WEB.wsCorTurProd.Update_Imagen_SitioResponse> Update_Imagen_SitioAsync(int id_imagen, int orden) {
            CT.ADIM.WEB.wsCorTurProd.Update_Imagen_SitioRequest inValue = new CT.ADIM.WEB.wsCorTurProd.Update_Imagen_SitioRequest();
            inValue.Body = new CT.ADIM.WEB.wsCorTurProd.Update_Imagen_SitioRequestBody();
            inValue.Body.id_imagen = id_imagen;
            inValue.Body.orden = orden;
            return ((CT.ADIM.WEB.wsCorTurProd.WSAdminSoap)(this)).Update_Imagen_SitioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CT.ADIM.WEB.wsCorTurProd.Delete_CircuitoResponse CT.ADIM.WEB.wsCorTurProd.WSAdminSoap.Delete_Circuito(CT.ADIM.WEB.wsCorTurProd.Delete_CircuitoRequest request) {
            return base.Channel.Delete_Circuito(request);
        }
        
        public string Delete_Circuito(int id_circuito) {
            CT.ADIM.WEB.wsCorTurProd.Delete_CircuitoRequest inValue = new CT.ADIM.WEB.wsCorTurProd.Delete_CircuitoRequest();
            inValue.Body = new CT.ADIM.WEB.wsCorTurProd.Delete_CircuitoRequestBody();
            inValue.Body.id_circuito = id_circuito;
            CT.ADIM.WEB.wsCorTurProd.Delete_CircuitoResponse retVal = ((CT.ADIM.WEB.wsCorTurProd.WSAdminSoap)(this)).Delete_Circuito(inValue);
            return retVal.Body.Delete_CircuitoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CT.ADIM.WEB.wsCorTurProd.Delete_CircuitoResponse> CT.ADIM.WEB.wsCorTurProd.WSAdminSoap.Delete_CircuitoAsync(CT.ADIM.WEB.wsCorTurProd.Delete_CircuitoRequest request) {
            return base.Channel.Delete_CircuitoAsync(request);
        }
        
        public System.Threading.Tasks.Task<CT.ADIM.WEB.wsCorTurProd.Delete_CircuitoResponse> Delete_CircuitoAsync(int id_circuito) {
            CT.ADIM.WEB.wsCorTurProd.Delete_CircuitoRequest inValue = new CT.ADIM.WEB.wsCorTurProd.Delete_CircuitoRequest();
            inValue.Body = new CT.ADIM.WEB.wsCorTurProd.Delete_CircuitoRequestBody();
            inValue.Body.id_circuito = id_circuito;
            return ((CT.ADIM.WEB.wsCorTurProd.WSAdminSoap)(this)).Delete_CircuitoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CT.ADIM.WEB.wsCorTurProd.Delete_SitioResponse CT.ADIM.WEB.wsCorTurProd.WSAdminSoap.Delete_Sitio(CT.ADIM.WEB.wsCorTurProd.Delete_SitioRequest request) {
            return base.Channel.Delete_Sitio(request);
        }
        
        public string Delete_Sitio(int id_sitio) {
            CT.ADIM.WEB.wsCorTurProd.Delete_SitioRequest inValue = new CT.ADIM.WEB.wsCorTurProd.Delete_SitioRequest();
            inValue.Body = new CT.ADIM.WEB.wsCorTurProd.Delete_SitioRequestBody();
            inValue.Body.id_sitio = id_sitio;
            CT.ADIM.WEB.wsCorTurProd.Delete_SitioResponse retVal = ((CT.ADIM.WEB.wsCorTurProd.WSAdminSoap)(this)).Delete_Sitio(inValue);
            return retVal.Body.Delete_SitioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CT.ADIM.WEB.wsCorTurProd.Delete_SitioResponse> CT.ADIM.WEB.wsCorTurProd.WSAdminSoap.Delete_SitioAsync(CT.ADIM.WEB.wsCorTurProd.Delete_SitioRequest request) {
            return base.Channel.Delete_SitioAsync(request);
        }
        
        public System.Threading.Tasks.Task<CT.ADIM.WEB.wsCorTurProd.Delete_SitioResponse> Delete_SitioAsync(int id_sitio) {
            CT.ADIM.WEB.wsCorTurProd.Delete_SitioRequest inValue = new CT.ADIM.WEB.wsCorTurProd.Delete_SitioRequest();
            inValue.Body = new CT.ADIM.WEB.wsCorTurProd.Delete_SitioRequestBody();
            inValue.Body.id_sitio = id_sitio;
            return ((CT.ADIM.WEB.wsCorTurProd.WSAdminSoap)(this)).Delete_SitioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CT.ADIM.WEB.wsCorTurProd.Delete_ImagenesResponse CT.ADIM.WEB.wsCorTurProd.WSAdminSoap.Delete_Imagenes(CT.ADIM.WEB.wsCorTurProd.Delete_ImagenesRequest request) {
            return base.Channel.Delete_Imagenes(request);
        }
        
        public string Delete_Imagenes(int id_imagen) {
            CT.ADIM.WEB.wsCorTurProd.Delete_ImagenesRequest inValue = new CT.ADIM.WEB.wsCorTurProd.Delete_ImagenesRequest();
            inValue.Body = new CT.ADIM.WEB.wsCorTurProd.Delete_ImagenesRequestBody();
            inValue.Body.id_imagen = id_imagen;
            CT.ADIM.WEB.wsCorTurProd.Delete_ImagenesResponse retVal = ((CT.ADIM.WEB.wsCorTurProd.WSAdminSoap)(this)).Delete_Imagenes(inValue);
            return retVal.Body.Delete_ImagenesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CT.ADIM.WEB.wsCorTurProd.Delete_ImagenesResponse> CT.ADIM.WEB.wsCorTurProd.WSAdminSoap.Delete_ImagenesAsync(CT.ADIM.WEB.wsCorTurProd.Delete_ImagenesRequest request) {
            return base.Channel.Delete_ImagenesAsync(request);
        }
        
        public System.Threading.Tasks.Task<CT.ADIM.WEB.wsCorTurProd.Delete_ImagenesResponse> Delete_ImagenesAsync(int id_imagen) {
            CT.ADIM.WEB.wsCorTurProd.Delete_ImagenesRequest inValue = new CT.ADIM.WEB.wsCorTurProd.Delete_ImagenesRequest();
            inValue.Body = new CT.ADIM.WEB.wsCorTurProd.Delete_ImagenesRequestBody();
            inValue.Body.id_imagen = id_imagen;
            return ((CT.ADIM.WEB.wsCorTurProd.WSAdminSoap)(this)).Delete_ImagenesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CT.ADIM.WEB.wsCorTurProd.Update_Info_WebResponse CT.ADIM.WEB.wsCorTurProd.WSAdminSoap.Update_Info_Web(CT.ADIM.WEB.wsCorTurProd.Update_Info_WebRequest request) {
            return base.Channel.Update_Info_Web(request);
        }
        
        public string Update_Info_Web() {
            CT.ADIM.WEB.wsCorTurProd.Update_Info_WebRequest inValue = new CT.ADIM.WEB.wsCorTurProd.Update_Info_WebRequest();
            inValue.Body = new CT.ADIM.WEB.wsCorTurProd.Update_Info_WebRequestBody();
            CT.ADIM.WEB.wsCorTurProd.Update_Info_WebResponse retVal = ((CT.ADIM.WEB.wsCorTurProd.WSAdminSoap)(this)).Update_Info_Web(inValue);
            return retVal.Body.Update_Info_WebResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CT.ADIM.WEB.wsCorTurProd.Update_Info_WebResponse> CT.ADIM.WEB.wsCorTurProd.WSAdminSoap.Update_Info_WebAsync(CT.ADIM.WEB.wsCorTurProd.Update_Info_WebRequest request) {
            return base.Channel.Update_Info_WebAsync(request);
        }
        
        public System.Threading.Tasks.Task<CT.ADIM.WEB.wsCorTurProd.Update_Info_WebResponse> Update_Info_WebAsync() {
            CT.ADIM.WEB.wsCorTurProd.Update_Info_WebRequest inValue = new CT.ADIM.WEB.wsCorTurProd.Update_Info_WebRequest();
            inValue.Body = new CT.ADIM.WEB.wsCorTurProd.Update_Info_WebRequestBody();
            return ((CT.ADIM.WEB.wsCorTurProd.WSAdminSoap)(this)).Update_Info_WebAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CT.ADIM.WEB.wsCorTurProd.Insert_Usuario_GuiaResponse CT.ADIM.WEB.wsCorTurProd.WSAdminSoap.Insert_Usuario_Guia(CT.ADIM.WEB.wsCorTurProd.Insert_Usuario_GuiaRequest request) {
            return base.Channel.Insert_Usuario_Guia(request);
        }
        
        public string Insert_Usuario_Guia(string nombres_usuario, string apellidos_usuario, string correo, string usuario, string contrasena, int numero_certificado, string Vigencia_Certificado, int ciudad, byte foto, byte foto_certificado) {
            CT.ADIM.WEB.wsCorTurProd.Insert_Usuario_GuiaRequest inValue = new CT.ADIM.WEB.wsCorTurProd.Insert_Usuario_GuiaRequest();
            inValue.Body = new CT.ADIM.WEB.wsCorTurProd.Insert_Usuario_GuiaRequestBody();
            inValue.Body.nombres_usuario = nombres_usuario;
            inValue.Body.apellidos_usuario = apellidos_usuario;
            inValue.Body.correo = correo;
            inValue.Body.usuario = usuario;
            inValue.Body.contrasena = contrasena;
            inValue.Body.numero_certificado = numero_certificado;
            inValue.Body.Vigencia_Certificado = Vigencia_Certificado;
            inValue.Body.ciudad = ciudad;
            inValue.Body.foto = foto;
            inValue.Body.foto_certificado = foto_certificado;
            CT.ADIM.WEB.wsCorTurProd.Insert_Usuario_GuiaResponse retVal = ((CT.ADIM.WEB.wsCorTurProd.WSAdminSoap)(this)).Insert_Usuario_Guia(inValue);
            return retVal.Body.Insert_Usuario_GuiaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CT.ADIM.WEB.wsCorTurProd.Insert_Usuario_GuiaResponse> CT.ADIM.WEB.wsCorTurProd.WSAdminSoap.Insert_Usuario_GuiaAsync(CT.ADIM.WEB.wsCorTurProd.Insert_Usuario_GuiaRequest request) {
            return base.Channel.Insert_Usuario_GuiaAsync(request);
        }
        
        public System.Threading.Tasks.Task<CT.ADIM.WEB.wsCorTurProd.Insert_Usuario_GuiaResponse> Insert_Usuario_GuiaAsync(string nombres_usuario, string apellidos_usuario, string correo, string usuario, string contrasena, int numero_certificado, string Vigencia_Certificado, int ciudad, byte foto, byte foto_certificado) {
            CT.ADIM.WEB.wsCorTurProd.Insert_Usuario_GuiaRequest inValue = new CT.ADIM.WEB.wsCorTurProd.Insert_Usuario_GuiaRequest();
            inValue.Body = new CT.ADIM.WEB.wsCorTurProd.Insert_Usuario_GuiaRequestBody();
            inValue.Body.nombres_usuario = nombres_usuario;
            inValue.Body.apellidos_usuario = apellidos_usuario;
            inValue.Body.correo = correo;
            inValue.Body.usuario = usuario;
            inValue.Body.contrasena = contrasena;
            inValue.Body.numero_certificado = numero_certificado;
            inValue.Body.Vigencia_Certificado = Vigencia_Certificado;
            inValue.Body.ciudad = ciudad;
            inValue.Body.foto = foto;
            inValue.Body.foto_certificado = foto_certificado;
            return ((CT.ADIM.WEB.wsCorTurProd.WSAdminSoap)(this)).Insert_Usuario_GuiaAsync(inValue);
        }
        
        public void TextSpeak() {
            base.Channel.TextSpeak();
        }
        
        public System.Threading.Tasks.Task TextSpeakAsync() {
            return base.Channel.TextSpeakAsync();
        }
    }
}
