//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CT.ADIM.WEB.wsCorTur {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsCorTur.WSAdminSoap")]
    public interface WSAdminSoap {
        
        // CODEGEN: Generating message contract since element name nombre from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert_Circuito", ReplyAction="*")]
        CT.ADIM.WEB.wsCorTur.Insert_CircuitoResponse Insert_Circuito(CT.ADIM.WEB.wsCorTur.Insert_CircuitoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert_Circuito", ReplyAction="*")]
        System.Threading.Tasks.Task<CT.ADIM.WEB.wsCorTur.Insert_CircuitoResponse> Insert_CircuitoAsync(CT.ADIM.WEB.wsCorTur.Insert_CircuitoRequest request);
        
        // CODEGEN: Generating message contract since element name id_circuito from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update_Circuito", ReplyAction="*")]
        CT.ADIM.WEB.wsCorTur.Update_CircuitoResponse Update_Circuito(CT.ADIM.WEB.wsCorTur.Update_CircuitoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update_Circuito", ReplyAction="*")]
        System.Threading.Tasks.Task<CT.ADIM.WEB.wsCorTur.Update_CircuitoResponse> Update_CircuitoAsync(CT.ADIM.WEB.wsCorTur.Update_CircuitoRequest request);
        
        // CODEGEN: Generating message contract since element name latitud from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert_Sitio", ReplyAction="*")]
        CT.ADIM.WEB.wsCorTur.Insert_SitioResponse Insert_Sitio(CT.ADIM.WEB.wsCorTur.Insert_SitioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert_Sitio", ReplyAction="*")]
        System.Threading.Tasks.Task<CT.ADIM.WEB.wsCorTur.Insert_SitioResponse> Insert_SitioAsync(CT.ADIM.WEB.wsCorTur.Insert_SitioRequest request);
        
        // CODEGEN: Generating message contract since element name id_sitio from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update_Sitio", ReplyAction="*")]
        CT.ADIM.WEB.wsCorTur.Update_SitioResponse Update_Sitio(CT.ADIM.WEB.wsCorTur.Update_SitioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update_Sitio", ReplyAction="*")]
        System.Threading.Tasks.Task<CT.ADIM.WEB.wsCorTur.Update_SitioResponse> Update_SitioAsync(CT.ADIM.WEB.wsCorTur.Update_SitioRequest request);
        
        // CODEGEN: Generating message contract since element name url_imagen from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert_Imagen_Sitio", ReplyAction="*")]
        CT.ADIM.WEB.wsCorTur.Insert_Imagen_SitioResponse Insert_Imagen_Sitio(CT.ADIM.WEB.wsCorTur.Insert_Imagen_SitioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Insert_Imagen_Sitio", ReplyAction="*")]
        System.Threading.Tasks.Task<CT.ADIM.WEB.wsCorTur.Insert_Imagen_SitioResponse> Insert_Imagen_SitioAsync(CT.ADIM.WEB.wsCorTur.Insert_Imagen_SitioRequest request);
        
        // CODEGEN: Generating message contract since element name Update_Imagen_SitioResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update_Imagen_Sitio", ReplyAction="*")]
        CT.ADIM.WEB.wsCorTur.Update_Imagen_SitioResponse Update_Imagen_Sitio(CT.ADIM.WEB.wsCorTur.Update_Imagen_SitioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update_Imagen_Sitio", ReplyAction="*")]
        System.Threading.Tasks.Task<CT.ADIM.WEB.wsCorTur.Update_Imagen_SitioResponse> Update_Imagen_SitioAsync(CT.ADIM.WEB.wsCorTur.Update_Imagen_SitioRequest request);
        
        // CODEGEN: Generating message contract since element name Delete_CircuitoResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete_Circuito", ReplyAction="*")]
        CT.ADIM.WEB.wsCorTur.Delete_CircuitoResponse Delete_Circuito(CT.ADIM.WEB.wsCorTur.Delete_CircuitoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete_Circuito", ReplyAction="*")]
        System.Threading.Tasks.Task<CT.ADIM.WEB.wsCorTur.Delete_CircuitoResponse> Delete_CircuitoAsync(CT.ADIM.WEB.wsCorTur.Delete_CircuitoRequest request);
        
        // CODEGEN: Generating message contract since element name Delete_SitioResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete_Sitio", ReplyAction="*")]
        CT.ADIM.WEB.wsCorTur.Delete_SitioResponse Delete_Sitio(CT.ADIM.WEB.wsCorTur.Delete_SitioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete_Sitio", ReplyAction="*")]
        System.Threading.Tasks.Task<CT.ADIM.WEB.wsCorTur.Delete_SitioResponse> Delete_SitioAsync(CT.ADIM.WEB.wsCorTur.Delete_SitioRequest request);
        
        // CODEGEN: Generating message contract since element name Delete_ImagenesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete_Imagenes", ReplyAction="*")]
        CT.ADIM.WEB.wsCorTur.Delete_ImagenesResponse Delete_Imagenes(CT.ADIM.WEB.wsCorTur.Delete_ImagenesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete_Imagenes", ReplyAction="*")]
        System.Threading.Tasks.Task<CT.ADIM.WEB.wsCorTur.Delete_ImagenesResponse> Delete_ImagenesAsync(CT.ADIM.WEB.wsCorTur.Delete_ImagenesRequest request);
        
        // CODEGEN: Generating message contract since element name Update_Info_WebResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update_Info_Web", ReplyAction="*")]
        CT.ADIM.WEB.wsCorTur.Update_Info_WebResponse Update_Info_Web(CT.ADIM.WEB.wsCorTur.Update_Info_WebRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update_Info_Web", ReplyAction="*")]
        System.Threading.Tasks.Task<CT.ADIM.WEB.wsCorTur.Update_Info_WebResponse> Update_Info_WebAsync(CT.ADIM.WEB.wsCorTur.Update_Info_WebRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TextSpeak", ReplyAction="*")]
        void TextSpeak();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TextSpeak", ReplyAction="*")]
        System.Threading.Tasks.Task TextSpeakAsync();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Insert_CircuitoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Insert_Circuito", Namespace="http://tempuri.org/", Order=0)]
        public CT.ADIM.WEB.wsCorTur.Insert_CircuitoRequestBody Body;
        
        public Insert_CircuitoRequest() {
        }
        
        public Insert_CircuitoRequest(CT.ADIM.WEB.wsCorTur.Insert_CircuitoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Insert_CircuitoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string descripcion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string recomendaciones;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string equipamento;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string edad;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string horario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string tiempo_estimado;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string codigo_idioma;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public int fk_categoria;
        
        public Insert_CircuitoRequestBody() {
        }
        
        public Insert_CircuitoRequestBody(string nombre, string descripcion, string recomendaciones, string equipamento, string edad, string horario, string tiempo_estimado, string codigo_idioma, int fk_categoria) {
            this.nombre = nombre;
            this.descripcion = descripcion;
            this.recomendaciones = recomendaciones;
            this.equipamento = equipamento;
            this.edad = edad;
            this.horario = horario;
            this.tiempo_estimado = tiempo_estimado;
            this.codigo_idioma = codigo_idioma;
            this.fk_categoria = fk_categoria;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Insert_CircuitoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Insert_CircuitoResponse", Namespace="http://tempuri.org/", Order=0)]
        public CT.ADIM.WEB.wsCorTur.Insert_CircuitoResponseBody Body;
        
        public Insert_CircuitoResponse() {
        }
        
        public Insert_CircuitoResponse(CT.ADIM.WEB.wsCorTur.Insert_CircuitoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Insert_CircuitoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Insert_CircuitoResult;
        
        public Insert_CircuitoResponseBody() {
        }
        
        public Insert_CircuitoResponseBody(string Insert_CircuitoResult) {
            this.Insert_CircuitoResult = Insert_CircuitoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Update_CircuitoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Update_Circuito", Namespace="http://tempuri.org/", Order=0)]
        public CT.ADIM.WEB.wsCorTur.Update_CircuitoRequestBody Body;
        
        public Update_CircuitoRequest() {
        }
        
        public Update_CircuitoRequest(CT.ADIM.WEB.wsCorTur.Update_CircuitoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Update_CircuitoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id_circuito;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string descripcion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string recomendaciones;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string equipamento;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string edad;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string horario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string tiempo_estimado;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string codigo_idioma;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public int fk_categoria;
        
        public Update_CircuitoRequestBody() {
        }
        
        public Update_CircuitoRequestBody(string id_circuito, string nombre, string descripcion, string recomendaciones, string equipamento, string edad, string horario, string tiempo_estimado, string codigo_idioma, int fk_categoria) {
            this.id_circuito = id_circuito;
            this.nombre = nombre;
            this.descripcion = descripcion;
            this.recomendaciones = recomendaciones;
            this.equipamento = equipamento;
            this.edad = edad;
            this.horario = horario;
            this.tiempo_estimado = tiempo_estimado;
            this.codigo_idioma = codigo_idioma;
            this.fk_categoria = fk_categoria;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Update_CircuitoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Update_CircuitoResponse", Namespace="http://tempuri.org/", Order=0)]
        public CT.ADIM.WEB.wsCorTur.Update_CircuitoResponseBody Body;
        
        public Update_CircuitoResponse() {
        }
        
        public Update_CircuitoResponse(CT.ADIM.WEB.wsCorTur.Update_CircuitoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Update_CircuitoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Update_CircuitoResult;
        
        public Update_CircuitoResponseBody() {
        }
        
        public Update_CircuitoResponseBody(string Update_CircuitoResult) {
            this.Update_CircuitoResult = Update_CircuitoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Insert_SitioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Insert_Sitio", Namespace="http://tempuri.org/", Order=0)]
        public CT.ADIM.WEB.wsCorTur.Insert_SitioRequestBody Body;
        
        public Insert_SitioRequest() {
        }
        
        public Insert_SitioRequest(CT.ADIM.WEB.wsCorTur.Insert_SitioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Insert_SitioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string latitud;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string longitud;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string direccion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string costo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ciudad;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string pais;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string descripcion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string equipamento;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string recomendaciones;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string tiempo_estimado;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string edad;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string horario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string codigo_idioma;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string telefono_sitio;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=15)]
        public int id_circuito;
        
        public Insert_SitioRequestBody() {
        }
        
        public Insert_SitioRequestBody(
                    string latitud, 
                    string longitud, 
                    string direccion, 
                    string costo, 
                    string ciudad, 
                    string pais, 
                    string nombre, 
                    string descripcion, 
                    string equipamento, 
                    string recomendaciones, 
                    string tiempo_estimado, 
                    string edad, 
                    string horario, 
                    string codigo_idioma, 
                    string telefono_sitio, 
                    int id_circuito) {
            this.latitud = latitud;
            this.longitud = longitud;
            this.direccion = direccion;
            this.costo = costo;
            this.ciudad = ciudad;
            this.pais = pais;
            this.nombre = nombre;
            this.descripcion = descripcion;
            this.equipamento = equipamento;
            this.recomendaciones = recomendaciones;
            this.tiempo_estimado = tiempo_estimado;
            this.edad = edad;
            this.horario = horario;
            this.codigo_idioma = codigo_idioma;
            this.telefono_sitio = telefono_sitio;
            this.id_circuito = id_circuito;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Insert_SitioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Insert_SitioResponse", Namespace="http://tempuri.org/", Order=0)]
        public CT.ADIM.WEB.wsCorTur.Insert_SitioResponseBody Body;
        
        public Insert_SitioResponse() {
        }
        
        public Insert_SitioResponse(CT.ADIM.WEB.wsCorTur.Insert_SitioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Insert_SitioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Insert_SitioResult;
        
        public Insert_SitioResponseBody() {
        }
        
        public Insert_SitioResponseBody(string Insert_SitioResult) {
            this.Insert_SitioResult = Insert_SitioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Update_SitioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Update_Sitio", Namespace="http://tempuri.org/", Order=0)]
        public CT.ADIM.WEB.wsCorTur.Update_SitioRequestBody Body;
        
        public Update_SitioRequest() {
        }
        
        public Update_SitioRequest(CT.ADIM.WEB.wsCorTur.Update_SitioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Update_SitioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id_sitio;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string latitud;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string longitud;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string direccion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string costo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string ciudad;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string pais;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string descripcion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string equipamento;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string recomendaciones;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string tiempo_estimado;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string edad;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string horario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string codigo_idioma;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string telefono_sitio;
        
        public Update_SitioRequestBody() {
        }
        
        public Update_SitioRequestBody(
                    string id_sitio, 
                    string latitud, 
                    string longitud, 
                    string direccion, 
                    string costo, 
                    string ciudad, 
                    string pais, 
                    string nombre, 
                    string descripcion, 
                    string equipamento, 
                    string recomendaciones, 
                    string tiempo_estimado, 
                    string edad, 
                    string horario, 
                    string codigo_idioma, 
                    string telefono_sitio) {
            this.id_sitio = id_sitio;
            this.latitud = latitud;
            this.longitud = longitud;
            this.direccion = direccion;
            this.costo = costo;
            this.ciudad = ciudad;
            this.pais = pais;
            this.nombre = nombre;
            this.descripcion = descripcion;
            this.equipamento = equipamento;
            this.recomendaciones = recomendaciones;
            this.tiempo_estimado = tiempo_estimado;
            this.edad = edad;
            this.horario = horario;
            this.codigo_idioma = codigo_idioma;
            this.telefono_sitio = telefono_sitio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Update_SitioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Update_SitioResponse", Namespace="http://tempuri.org/", Order=0)]
        public CT.ADIM.WEB.wsCorTur.Update_SitioResponseBody Body;
        
        public Update_SitioResponse() {
        }
        
        public Update_SitioResponse(CT.ADIM.WEB.wsCorTur.Update_SitioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Update_SitioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Update_SitioResult;
        
        public Update_SitioResponseBody() {
        }
        
        public Update_SitioResponseBody(string Update_SitioResult) {
            this.Update_SitioResult = Update_SitioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Insert_Imagen_SitioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Insert_Imagen_Sitio", Namespace="http://tempuri.org/", Order=0)]
        public CT.ADIM.WEB.wsCorTur.Insert_Imagen_SitioRequestBody Body;
        
        public Insert_Imagen_SitioRequest() {
        }
        
        public Insert_Imagen_SitioRequest(CT.ADIM.WEB.wsCorTur.Insert_Imagen_SitioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Insert_Imagen_SitioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string url_imagen;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int fk_sitio;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int orden;
        
        public Insert_Imagen_SitioRequestBody() {
        }
        
        public Insert_Imagen_SitioRequestBody(string url_imagen, int fk_sitio, int orden) {
            this.url_imagen = url_imagen;
            this.fk_sitio = fk_sitio;
            this.orden = orden;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Insert_Imagen_SitioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Insert_Imagen_SitioResponse", Namespace="http://tempuri.org/", Order=0)]
        public CT.ADIM.WEB.wsCorTur.Insert_Imagen_SitioResponseBody Body;
        
        public Insert_Imagen_SitioResponse() {
        }
        
        public Insert_Imagen_SitioResponse(CT.ADIM.WEB.wsCorTur.Insert_Imagen_SitioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Insert_Imagen_SitioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Insert_Imagen_SitioResult;
        
        public Insert_Imagen_SitioResponseBody() {
        }
        
        public Insert_Imagen_SitioResponseBody(string Insert_Imagen_SitioResult) {
            this.Insert_Imagen_SitioResult = Insert_Imagen_SitioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Update_Imagen_SitioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Update_Imagen_Sitio", Namespace="http://tempuri.org/", Order=0)]
        public CT.ADIM.WEB.wsCorTur.Update_Imagen_SitioRequestBody Body;
        
        public Update_Imagen_SitioRequest() {
        }
        
        public Update_Imagen_SitioRequest(CT.ADIM.WEB.wsCorTur.Update_Imagen_SitioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Update_Imagen_SitioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id_imagen;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int orden;
        
        public Update_Imagen_SitioRequestBody() {
        }
        
        public Update_Imagen_SitioRequestBody(int id_imagen, int orden) {
            this.id_imagen = id_imagen;
            this.orden = orden;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Update_Imagen_SitioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Update_Imagen_SitioResponse", Namespace="http://tempuri.org/", Order=0)]
        public CT.ADIM.WEB.wsCorTur.Update_Imagen_SitioResponseBody Body;
        
        public Update_Imagen_SitioResponse() {
        }
        
        public Update_Imagen_SitioResponse(CT.ADIM.WEB.wsCorTur.Update_Imagen_SitioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Update_Imagen_SitioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Update_Imagen_SitioResult;
        
        public Update_Imagen_SitioResponseBody() {
        }
        
        public Update_Imagen_SitioResponseBody(string Update_Imagen_SitioResult) {
            this.Update_Imagen_SitioResult = Update_Imagen_SitioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Delete_CircuitoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Delete_Circuito", Namespace="http://tempuri.org/", Order=0)]
        public CT.ADIM.WEB.wsCorTur.Delete_CircuitoRequestBody Body;
        
        public Delete_CircuitoRequest() {
        }
        
        public Delete_CircuitoRequest(CT.ADIM.WEB.wsCorTur.Delete_CircuitoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Delete_CircuitoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id_circuito;
        
        public Delete_CircuitoRequestBody() {
        }
        
        public Delete_CircuitoRequestBody(int id_circuito) {
            this.id_circuito = id_circuito;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Delete_CircuitoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Delete_CircuitoResponse", Namespace="http://tempuri.org/", Order=0)]
        public CT.ADIM.WEB.wsCorTur.Delete_CircuitoResponseBody Body;
        
        public Delete_CircuitoResponse() {
        }
        
        public Delete_CircuitoResponse(CT.ADIM.WEB.wsCorTur.Delete_CircuitoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Delete_CircuitoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Delete_CircuitoResult;
        
        public Delete_CircuitoResponseBody() {
        }
        
        public Delete_CircuitoResponseBody(string Delete_CircuitoResult) {
            this.Delete_CircuitoResult = Delete_CircuitoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Delete_SitioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Delete_Sitio", Namespace="http://tempuri.org/", Order=0)]
        public CT.ADIM.WEB.wsCorTur.Delete_SitioRequestBody Body;
        
        public Delete_SitioRequest() {
        }
        
        public Delete_SitioRequest(CT.ADIM.WEB.wsCorTur.Delete_SitioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Delete_SitioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id_sitio;
        
        public Delete_SitioRequestBody() {
        }
        
        public Delete_SitioRequestBody(int id_sitio) {
            this.id_sitio = id_sitio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Delete_SitioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Delete_SitioResponse", Namespace="http://tempuri.org/", Order=0)]
        public CT.ADIM.WEB.wsCorTur.Delete_SitioResponseBody Body;
        
        public Delete_SitioResponse() {
        }
        
        public Delete_SitioResponse(CT.ADIM.WEB.wsCorTur.Delete_SitioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Delete_SitioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Delete_SitioResult;
        
        public Delete_SitioResponseBody() {
        }
        
        public Delete_SitioResponseBody(string Delete_SitioResult) {
            this.Delete_SitioResult = Delete_SitioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Delete_ImagenesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Delete_Imagenes", Namespace="http://tempuri.org/", Order=0)]
        public CT.ADIM.WEB.wsCorTur.Delete_ImagenesRequestBody Body;
        
        public Delete_ImagenesRequest() {
        }
        
        public Delete_ImagenesRequest(CT.ADIM.WEB.wsCorTur.Delete_ImagenesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Delete_ImagenesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id_imagen;
        
        public Delete_ImagenesRequestBody() {
        }
        
        public Delete_ImagenesRequestBody(int id_imagen) {
            this.id_imagen = id_imagen;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Delete_ImagenesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Delete_ImagenesResponse", Namespace="http://tempuri.org/", Order=0)]
        public CT.ADIM.WEB.wsCorTur.Delete_ImagenesResponseBody Body;
        
        public Delete_ImagenesResponse() {
        }
        
        public Delete_ImagenesResponse(CT.ADIM.WEB.wsCorTur.Delete_ImagenesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Delete_ImagenesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Delete_ImagenesResult;
        
        public Delete_ImagenesResponseBody() {
        }
        
        public Delete_ImagenesResponseBody(string Delete_ImagenesResult) {
            this.Delete_ImagenesResult = Delete_ImagenesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Update_Info_WebRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Update_Info_Web", Namespace="http://tempuri.org/", Order=0)]
        public CT.ADIM.WEB.wsCorTur.Update_Info_WebRequestBody Body;
        
        public Update_Info_WebRequest() {
        }
        
        public Update_Info_WebRequest(CT.ADIM.WEB.wsCorTur.Update_Info_WebRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class Update_Info_WebRequestBody {
        
        public Update_Info_WebRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Update_Info_WebResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Update_Info_WebResponse", Namespace="http://tempuri.org/", Order=0)]
        public CT.ADIM.WEB.wsCorTur.Update_Info_WebResponseBody Body;
        
        public Update_Info_WebResponse() {
        }
        
        public Update_Info_WebResponse(CT.ADIM.WEB.wsCorTur.Update_Info_WebResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Update_Info_WebResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Update_Info_WebResult;
        
        public Update_Info_WebResponseBody() {
        }
        
        public Update_Info_WebResponseBody(string Update_Info_WebResult) {
            this.Update_Info_WebResult = Update_Info_WebResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSAdminSoapChannel : CT.ADIM.WEB.wsCorTur.WSAdminSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSAdminSoapClient : System.ServiceModel.ClientBase<CT.ADIM.WEB.wsCorTur.WSAdminSoap>, CT.ADIM.WEB.wsCorTur.WSAdminSoap {
        
        public WSAdminSoapClient() {
        }
        
        public WSAdminSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSAdminSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSAdminSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSAdminSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CT.ADIM.WEB.wsCorTur.Insert_CircuitoResponse CT.ADIM.WEB.wsCorTur.WSAdminSoap.Insert_Circuito(CT.ADIM.WEB.wsCorTur.Insert_CircuitoRequest request) {
            return base.Channel.Insert_Circuito(request);
        }
        
        public string Insert_Circuito(string nombre, string descripcion, string recomendaciones, string equipamento, string edad, string horario, string tiempo_estimado, string codigo_idioma, int fk_categoria) {
            CT.ADIM.WEB.wsCorTur.Insert_CircuitoRequest inValue = new CT.ADIM.WEB.wsCorTur.Insert_CircuitoRequest();
            inValue.Body = new CT.ADIM.WEB.wsCorTur.Insert_CircuitoRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.descripcion = descripcion;
            inValue.Body.recomendaciones = recomendaciones;
            inValue.Body.equipamento = equipamento;
            inValue.Body.edad = edad;
            inValue.Body.horario = horario;
            inValue.Body.tiempo_estimado = tiempo_estimado;
            inValue.Body.codigo_idioma = codigo_idioma;
            inValue.Body.fk_categoria = fk_categoria;
            CT.ADIM.WEB.wsCorTur.Insert_CircuitoResponse retVal = ((CT.ADIM.WEB.wsCorTur.WSAdminSoap)(this)).Insert_Circuito(inValue);
            return retVal.Body.Insert_CircuitoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CT.ADIM.WEB.wsCorTur.Insert_CircuitoResponse> CT.ADIM.WEB.wsCorTur.WSAdminSoap.Insert_CircuitoAsync(CT.ADIM.WEB.wsCorTur.Insert_CircuitoRequest request) {
            return base.Channel.Insert_CircuitoAsync(request);
        }
        
        public System.Threading.Tasks.Task<CT.ADIM.WEB.wsCorTur.Insert_CircuitoResponse> Insert_CircuitoAsync(string nombre, string descripcion, string recomendaciones, string equipamento, string edad, string horario, string tiempo_estimado, string codigo_idioma, int fk_categoria) {
            CT.ADIM.WEB.wsCorTur.Insert_CircuitoRequest inValue = new CT.ADIM.WEB.wsCorTur.Insert_CircuitoRequest();
            inValue.Body = new CT.ADIM.WEB.wsCorTur.Insert_CircuitoRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.descripcion = descripcion;
            inValue.Body.recomendaciones = recomendaciones;
            inValue.Body.equipamento = equipamento;
            inValue.Body.edad = edad;
            inValue.Body.horario = horario;
            inValue.Body.tiempo_estimado = tiempo_estimado;
            inValue.Body.codigo_idioma = codigo_idioma;
            inValue.Body.fk_categoria = fk_categoria;
            return ((CT.ADIM.WEB.wsCorTur.WSAdminSoap)(this)).Insert_CircuitoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CT.ADIM.WEB.wsCorTur.Update_CircuitoResponse CT.ADIM.WEB.wsCorTur.WSAdminSoap.Update_Circuito(CT.ADIM.WEB.wsCorTur.Update_CircuitoRequest request) {
            return base.Channel.Update_Circuito(request);
        }
        
        public string Update_Circuito(string id_circuito, string nombre, string descripcion, string recomendaciones, string equipamento, string edad, string horario, string tiempo_estimado, string codigo_idioma, int fk_categoria) {
            CT.ADIM.WEB.wsCorTur.Update_CircuitoRequest inValue = new CT.ADIM.WEB.wsCorTur.Update_CircuitoRequest();
            inValue.Body = new CT.ADIM.WEB.wsCorTur.Update_CircuitoRequestBody();
            inValue.Body.id_circuito = id_circuito;
            inValue.Body.nombre = nombre;
            inValue.Body.descripcion = descripcion;
            inValue.Body.recomendaciones = recomendaciones;
            inValue.Body.equipamento = equipamento;
            inValue.Body.edad = edad;
            inValue.Body.horario = horario;
            inValue.Body.tiempo_estimado = tiempo_estimado;
            inValue.Body.codigo_idioma = codigo_idioma;
            inValue.Body.fk_categoria = fk_categoria;
            CT.ADIM.WEB.wsCorTur.Update_CircuitoResponse retVal = ((CT.ADIM.WEB.wsCorTur.WSAdminSoap)(this)).Update_Circuito(inValue);
            return retVal.Body.Update_CircuitoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CT.ADIM.WEB.wsCorTur.Update_CircuitoResponse> CT.ADIM.WEB.wsCorTur.WSAdminSoap.Update_CircuitoAsync(CT.ADIM.WEB.wsCorTur.Update_CircuitoRequest request) {
            return base.Channel.Update_CircuitoAsync(request);
        }
        
        public System.Threading.Tasks.Task<CT.ADIM.WEB.wsCorTur.Update_CircuitoResponse> Update_CircuitoAsync(string id_circuito, string nombre, string descripcion, string recomendaciones, string equipamento, string edad, string horario, string tiempo_estimado, string codigo_idioma, int fk_categoria) {
            CT.ADIM.WEB.wsCorTur.Update_CircuitoRequest inValue = new CT.ADIM.WEB.wsCorTur.Update_CircuitoRequest();
            inValue.Body = new CT.ADIM.WEB.wsCorTur.Update_CircuitoRequestBody();
            inValue.Body.id_circuito = id_circuito;
            inValue.Body.nombre = nombre;
            inValue.Body.descripcion = descripcion;
            inValue.Body.recomendaciones = recomendaciones;
            inValue.Body.equipamento = equipamento;
            inValue.Body.edad = edad;
            inValue.Body.horario = horario;
            inValue.Body.tiempo_estimado = tiempo_estimado;
            inValue.Body.codigo_idioma = codigo_idioma;
            inValue.Body.fk_categoria = fk_categoria;
            return ((CT.ADIM.WEB.wsCorTur.WSAdminSoap)(this)).Update_CircuitoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CT.ADIM.WEB.wsCorTur.Insert_SitioResponse CT.ADIM.WEB.wsCorTur.WSAdminSoap.Insert_Sitio(CT.ADIM.WEB.wsCorTur.Insert_SitioRequest request) {
            return base.Channel.Insert_Sitio(request);
        }
        
        public string Insert_Sitio(
                    string latitud, 
                    string longitud, 
                    string direccion, 
                    string costo, 
                    string ciudad, 
                    string pais, 
                    string nombre, 
                    string descripcion, 
                    string equipamento, 
                    string recomendaciones, 
                    string tiempo_estimado, 
                    string edad, 
                    string horario, 
                    string codigo_idioma, 
                    string telefono_sitio, 
                    int id_circuito) {
            CT.ADIM.WEB.wsCorTur.Insert_SitioRequest inValue = new CT.ADIM.WEB.wsCorTur.Insert_SitioRequest();
            inValue.Body = new CT.ADIM.WEB.wsCorTur.Insert_SitioRequestBody();
            inValue.Body.latitud = latitud;
            inValue.Body.longitud = longitud;
            inValue.Body.direccion = direccion;
            inValue.Body.costo = costo;
            inValue.Body.ciudad = ciudad;
            inValue.Body.pais = pais;
            inValue.Body.nombre = nombre;
            inValue.Body.descripcion = descripcion;
            inValue.Body.equipamento = equipamento;
            inValue.Body.recomendaciones = recomendaciones;
            inValue.Body.tiempo_estimado = tiempo_estimado;
            inValue.Body.edad = edad;
            inValue.Body.horario = horario;
            inValue.Body.codigo_idioma = codigo_idioma;
            inValue.Body.telefono_sitio = telefono_sitio;
            inValue.Body.id_circuito = id_circuito;
            CT.ADIM.WEB.wsCorTur.Insert_SitioResponse retVal = ((CT.ADIM.WEB.wsCorTur.WSAdminSoap)(this)).Insert_Sitio(inValue);
            return retVal.Body.Insert_SitioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CT.ADIM.WEB.wsCorTur.Insert_SitioResponse> CT.ADIM.WEB.wsCorTur.WSAdminSoap.Insert_SitioAsync(CT.ADIM.WEB.wsCorTur.Insert_SitioRequest request) {
            return base.Channel.Insert_SitioAsync(request);
        }
        
        public System.Threading.Tasks.Task<CT.ADIM.WEB.wsCorTur.Insert_SitioResponse> Insert_SitioAsync(
                    string latitud, 
                    string longitud, 
                    string direccion, 
                    string costo, 
                    string ciudad, 
                    string pais, 
                    string nombre, 
                    string descripcion, 
                    string equipamento, 
                    string recomendaciones, 
                    string tiempo_estimado, 
                    string edad, 
                    string horario, 
                    string codigo_idioma, 
                    string telefono_sitio, 
                    int id_circuito) {
            CT.ADIM.WEB.wsCorTur.Insert_SitioRequest inValue = new CT.ADIM.WEB.wsCorTur.Insert_SitioRequest();
            inValue.Body = new CT.ADIM.WEB.wsCorTur.Insert_SitioRequestBody();
            inValue.Body.latitud = latitud;
            inValue.Body.longitud = longitud;
            inValue.Body.direccion = direccion;
            inValue.Body.costo = costo;
            inValue.Body.ciudad = ciudad;
            inValue.Body.pais = pais;
            inValue.Body.nombre = nombre;
            inValue.Body.descripcion = descripcion;
            inValue.Body.equipamento = equipamento;
            inValue.Body.recomendaciones = recomendaciones;
            inValue.Body.tiempo_estimado = tiempo_estimado;
            inValue.Body.edad = edad;
            inValue.Body.horario = horario;
            inValue.Body.codigo_idioma = codigo_idioma;
            inValue.Body.telefono_sitio = telefono_sitio;
            inValue.Body.id_circuito = id_circuito;
            return ((CT.ADIM.WEB.wsCorTur.WSAdminSoap)(this)).Insert_SitioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CT.ADIM.WEB.wsCorTur.Update_SitioResponse CT.ADIM.WEB.wsCorTur.WSAdminSoap.Update_Sitio(CT.ADIM.WEB.wsCorTur.Update_SitioRequest request) {
            return base.Channel.Update_Sitio(request);
        }
        
        public string Update_Sitio(
                    string id_sitio, 
                    string latitud, 
                    string longitud, 
                    string direccion, 
                    string costo, 
                    string ciudad, 
                    string pais, 
                    string nombre, 
                    string descripcion, 
                    string equipamento, 
                    string recomendaciones, 
                    string tiempo_estimado, 
                    string edad, 
                    string horario, 
                    string codigo_idioma, 
                    string telefono_sitio) {
            CT.ADIM.WEB.wsCorTur.Update_SitioRequest inValue = new CT.ADIM.WEB.wsCorTur.Update_SitioRequest();
            inValue.Body = new CT.ADIM.WEB.wsCorTur.Update_SitioRequestBody();
            inValue.Body.id_sitio = id_sitio;
            inValue.Body.latitud = latitud;
            inValue.Body.longitud = longitud;
            inValue.Body.direccion = direccion;
            inValue.Body.costo = costo;
            inValue.Body.ciudad = ciudad;
            inValue.Body.pais = pais;
            inValue.Body.nombre = nombre;
            inValue.Body.descripcion = descripcion;
            inValue.Body.equipamento = equipamento;
            inValue.Body.recomendaciones = recomendaciones;
            inValue.Body.tiempo_estimado = tiempo_estimado;
            inValue.Body.edad = edad;
            inValue.Body.horario = horario;
            inValue.Body.codigo_idioma = codigo_idioma;
            inValue.Body.telefono_sitio = telefono_sitio;
            CT.ADIM.WEB.wsCorTur.Update_SitioResponse retVal = ((CT.ADIM.WEB.wsCorTur.WSAdminSoap)(this)).Update_Sitio(inValue);
            return retVal.Body.Update_SitioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CT.ADIM.WEB.wsCorTur.Update_SitioResponse> CT.ADIM.WEB.wsCorTur.WSAdminSoap.Update_SitioAsync(CT.ADIM.WEB.wsCorTur.Update_SitioRequest request) {
            return base.Channel.Update_SitioAsync(request);
        }
        
        public System.Threading.Tasks.Task<CT.ADIM.WEB.wsCorTur.Update_SitioResponse> Update_SitioAsync(
                    string id_sitio, 
                    string latitud, 
                    string longitud, 
                    string direccion, 
                    string costo, 
                    string ciudad, 
                    string pais, 
                    string nombre, 
                    string descripcion, 
                    string equipamento, 
                    string recomendaciones, 
                    string tiempo_estimado, 
                    string edad, 
                    string horario, 
                    string codigo_idioma, 
                    string telefono_sitio) {
            CT.ADIM.WEB.wsCorTur.Update_SitioRequest inValue = new CT.ADIM.WEB.wsCorTur.Update_SitioRequest();
            inValue.Body = new CT.ADIM.WEB.wsCorTur.Update_SitioRequestBody();
            inValue.Body.id_sitio = id_sitio;
            inValue.Body.latitud = latitud;
            inValue.Body.longitud = longitud;
            inValue.Body.direccion = direccion;
            inValue.Body.costo = costo;
            inValue.Body.ciudad = ciudad;
            inValue.Body.pais = pais;
            inValue.Body.nombre = nombre;
            inValue.Body.descripcion = descripcion;
            inValue.Body.equipamento = equipamento;
            inValue.Body.recomendaciones = recomendaciones;
            inValue.Body.tiempo_estimado = tiempo_estimado;
            inValue.Body.edad = edad;
            inValue.Body.horario = horario;
            inValue.Body.codigo_idioma = codigo_idioma;
            inValue.Body.telefono_sitio = telefono_sitio;
            return ((CT.ADIM.WEB.wsCorTur.WSAdminSoap)(this)).Update_SitioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CT.ADIM.WEB.wsCorTur.Insert_Imagen_SitioResponse CT.ADIM.WEB.wsCorTur.WSAdminSoap.Insert_Imagen_Sitio(CT.ADIM.WEB.wsCorTur.Insert_Imagen_SitioRequest request) {
            return base.Channel.Insert_Imagen_Sitio(request);
        }
        
        public string Insert_Imagen_Sitio(string url_imagen, int fk_sitio, int orden) {
            CT.ADIM.WEB.wsCorTur.Insert_Imagen_SitioRequest inValue = new CT.ADIM.WEB.wsCorTur.Insert_Imagen_SitioRequest();
            inValue.Body = new CT.ADIM.WEB.wsCorTur.Insert_Imagen_SitioRequestBody();
            inValue.Body.url_imagen = url_imagen;
            inValue.Body.fk_sitio = fk_sitio;
            inValue.Body.orden = orden;
            CT.ADIM.WEB.wsCorTur.Insert_Imagen_SitioResponse retVal = ((CT.ADIM.WEB.wsCorTur.WSAdminSoap)(this)).Insert_Imagen_Sitio(inValue);
            return retVal.Body.Insert_Imagen_SitioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CT.ADIM.WEB.wsCorTur.Insert_Imagen_SitioResponse> CT.ADIM.WEB.wsCorTur.WSAdminSoap.Insert_Imagen_SitioAsync(CT.ADIM.WEB.wsCorTur.Insert_Imagen_SitioRequest request) {
            return base.Channel.Insert_Imagen_SitioAsync(request);
        }
        
        public System.Threading.Tasks.Task<CT.ADIM.WEB.wsCorTur.Insert_Imagen_SitioResponse> Insert_Imagen_SitioAsync(string url_imagen, int fk_sitio, int orden) {
            CT.ADIM.WEB.wsCorTur.Insert_Imagen_SitioRequest inValue = new CT.ADIM.WEB.wsCorTur.Insert_Imagen_SitioRequest();
            inValue.Body = new CT.ADIM.WEB.wsCorTur.Insert_Imagen_SitioRequestBody();
            inValue.Body.url_imagen = url_imagen;
            inValue.Body.fk_sitio = fk_sitio;
            inValue.Body.orden = orden;
            return ((CT.ADIM.WEB.wsCorTur.WSAdminSoap)(this)).Insert_Imagen_SitioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CT.ADIM.WEB.wsCorTur.Update_Imagen_SitioResponse CT.ADIM.WEB.wsCorTur.WSAdminSoap.Update_Imagen_Sitio(CT.ADIM.WEB.wsCorTur.Update_Imagen_SitioRequest request) {
            return base.Channel.Update_Imagen_Sitio(request);
        }
        
        public string Update_Imagen_Sitio(int id_imagen, int orden) {
            CT.ADIM.WEB.wsCorTur.Update_Imagen_SitioRequest inValue = new CT.ADIM.WEB.wsCorTur.Update_Imagen_SitioRequest();
            inValue.Body = new CT.ADIM.WEB.wsCorTur.Update_Imagen_SitioRequestBody();
            inValue.Body.id_imagen = id_imagen;
            inValue.Body.orden = orden;
            CT.ADIM.WEB.wsCorTur.Update_Imagen_SitioResponse retVal = ((CT.ADIM.WEB.wsCorTur.WSAdminSoap)(this)).Update_Imagen_Sitio(inValue);
            return retVal.Body.Update_Imagen_SitioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CT.ADIM.WEB.wsCorTur.Update_Imagen_SitioResponse> CT.ADIM.WEB.wsCorTur.WSAdminSoap.Update_Imagen_SitioAsync(CT.ADIM.WEB.wsCorTur.Update_Imagen_SitioRequest request) {
            return base.Channel.Update_Imagen_SitioAsync(request);
        }
        
        public System.Threading.Tasks.Task<CT.ADIM.WEB.wsCorTur.Update_Imagen_SitioResponse> Update_Imagen_SitioAsync(int id_imagen, int orden) {
            CT.ADIM.WEB.wsCorTur.Update_Imagen_SitioRequest inValue = new CT.ADIM.WEB.wsCorTur.Update_Imagen_SitioRequest();
            inValue.Body = new CT.ADIM.WEB.wsCorTur.Update_Imagen_SitioRequestBody();
            inValue.Body.id_imagen = id_imagen;
            inValue.Body.orden = orden;
            return ((CT.ADIM.WEB.wsCorTur.WSAdminSoap)(this)).Update_Imagen_SitioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CT.ADIM.WEB.wsCorTur.Delete_CircuitoResponse CT.ADIM.WEB.wsCorTur.WSAdminSoap.Delete_Circuito(CT.ADIM.WEB.wsCorTur.Delete_CircuitoRequest request) {
            return base.Channel.Delete_Circuito(request);
        }
        
        public string Delete_Circuito(int id_circuito) {
            CT.ADIM.WEB.wsCorTur.Delete_CircuitoRequest inValue = new CT.ADIM.WEB.wsCorTur.Delete_CircuitoRequest();
            inValue.Body = new CT.ADIM.WEB.wsCorTur.Delete_CircuitoRequestBody();
            inValue.Body.id_circuito = id_circuito;
            CT.ADIM.WEB.wsCorTur.Delete_CircuitoResponse retVal = ((CT.ADIM.WEB.wsCorTur.WSAdminSoap)(this)).Delete_Circuito(inValue);
            return retVal.Body.Delete_CircuitoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CT.ADIM.WEB.wsCorTur.Delete_CircuitoResponse> CT.ADIM.WEB.wsCorTur.WSAdminSoap.Delete_CircuitoAsync(CT.ADIM.WEB.wsCorTur.Delete_CircuitoRequest request) {
            return base.Channel.Delete_CircuitoAsync(request);
        }
        
        public System.Threading.Tasks.Task<CT.ADIM.WEB.wsCorTur.Delete_CircuitoResponse> Delete_CircuitoAsync(int id_circuito) {
            CT.ADIM.WEB.wsCorTur.Delete_CircuitoRequest inValue = new CT.ADIM.WEB.wsCorTur.Delete_CircuitoRequest();
            inValue.Body = new CT.ADIM.WEB.wsCorTur.Delete_CircuitoRequestBody();
            inValue.Body.id_circuito = id_circuito;
            return ((CT.ADIM.WEB.wsCorTur.WSAdminSoap)(this)).Delete_CircuitoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CT.ADIM.WEB.wsCorTur.Delete_SitioResponse CT.ADIM.WEB.wsCorTur.WSAdminSoap.Delete_Sitio(CT.ADIM.WEB.wsCorTur.Delete_SitioRequest request) {
            return base.Channel.Delete_Sitio(request);
        }
        
        public string Delete_Sitio(int id_sitio) {
            CT.ADIM.WEB.wsCorTur.Delete_SitioRequest inValue = new CT.ADIM.WEB.wsCorTur.Delete_SitioRequest();
            inValue.Body = new CT.ADIM.WEB.wsCorTur.Delete_SitioRequestBody();
            inValue.Body.id_sitio = id_sitio;
            CT.ADIM.WEB.wsCorTur.Delete_SitioResponse retVal = ((CT.ADIM.WEB.wsCorTur.WSAdminSoap)(this)).Delete_Sitio(inValue);
            return retVal.Body.Delete_SitioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CT.ADIM.WEB.wsCorTur.Delete_SitioResponse> CT.ADIM.WEB.wsCorTur.WSAdminSoap.Delete_SitioAsync(CT.ADIM.WEB.wsCorTur.Delete_SitioRequest request) {
            return base.Channel.Delete_SitioAsync(request);
        }
        
        public System.Threading.Tasks.Task<CT.ADIM.WEB.wsCorTur.Delete_SitioResponse> Delete_SitioAsync(int id_sitio) {
            CT.ADIM.WEB.wsCorTur.Delete_SitioRequest inValue = new CT.ADIM.WEB.wsCorTur.Delete_SitioRequest();
            inValue.Body = new CT.ADIM.WEB.wsCorTur.Delete_SitioRequestBody();
            inValue.Body.id_sitio = id_sitio;
            return ((CT.ADIM.WEB.wsCorTur.WSAdminSoap)(this)).Delete_SitioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CT.ADIM.WEB.wsCorTur.Delete_ImagenesResponse CT.ADIM.WEB.wsCorTur.WSAdminSoap.Delete_Imagenes(CT.ADIM.WEB.wsCorTur.Delete_ImagenesRequest request) {
            return base.Channel.Delete_Imagenes(request);
        }
        
        public string Delete_Imagenes(int id_imagen) {
            CT.ADIM.WEB.wsCorTur.Delete_ImagenesRequest inValue = new CT.ADIM.WEB.wsCorTur.Delete_ImagenesRequest();
            inValue.Body = new CT.ADIM.WEB.wsCorTur.Delete_ImagenesRequestBody();
            inValue.Body.id_imagen = id_imagen;
            CT.ADIM.WEB.wsCorTur.Delete_ImagenesResponse retVal = ((CT.ADIM.WEB.wsCorTur.WSAdminSoap)(this)).Delete_Imagenes(inValue);
            return retVal.Body.Delete_ImagenesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CT.ADIM.WEB.wsCorTur.Delete_ImagenesResponse> CT.ADIM.WEB.wsCorTur.WSAdminSoap.Delete_ImagenesAsync(CT.ADIM.WEB.wsCorTur.Delete_ImagenesRequest request) {
            return base.Channel.Delete_ImagenesAsync(request);
        }
        
        public System.Threading.Tasks.Task<CT.ADIM.WEB.wsCorTur.Delete_ImagenesResponse> Delete_ImagenesAsync(int id_imagen) {
            CT.ADIM.WEB.wsCorTur.Delete_ImagenesRequest inValue = new CT.ADIM.WEB.wsCorTur.Delete_ImagenesRequest();
            inValue.Body = new CT.ADIM.WEB.wsCorTur.Delete_ImagenesRequestBody();
            inValue.Body.id_imagen = id_imagen;
            return ((CT.ADIM.WEB.wsCorTur.WSAdminSoap)(this)).Delete_ImagenesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CT.ADIM.WEB.wsCorTur.Update_Info_WebResponse CT.ADIM.WEB.wsCorTur.WSAdminSoap.Update_Info_Web(CT.ADIM.WEB.wsCorTur.Update_Info_WebRequest request) {
            return base.Channel.Update_Info_Web(request);
        }
        
        public string Update_Info_Web() {
            CT.ADIM.WEB.wsCorTur.Update_Info_WebRequest inValue = new CT.ADIM.WEB.wsCorTur.Update_Info_WebRequest();
            inValue.Body = new CT.ADIM.WEB.wsCorTur.Update_Info_WebRequestBody();
            CT.ADIM.WEB.wsCorTur.Update_Info_WebResponse retVal = ((CT.ADIM.WEB.wsCorTur.WSAdminSoap)(this)).Update_Info_Web(inValue);
            return retVal.Body.Update_Info_WebResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CT.ADIM.WEB.wsCorTur.Update_Info_WebResponse> CT.ADIM.WEB.wsCorTur.WSAdminSoap.Update_Info_WebAsync(CT.ADIM.WEB.wsCorTur.Update_Info_WebRequest request) {
            return base.Channel.Update_Info_WebAsync(request);
        }
        
        public System.Threading.Tasks.Task<CT.ADIM.WEB.wsCorTur.Update_Info_WebResponse> Update_Info_WebAsync() {
            CT.ADIM.WEB.wsCorTur.Update_Info_WebRequest inValue = new CT.ADIM.WEB.wsCorTur.Update_Info_WebRequest();
            inValue.Body = new CT.ADIM.WEB.wsCorTur.Update_Info_WebRequestBody();
            return ((CT.ADIM.WEB.wsCorTur.WSAdminSoap)(this)).Update_Info_WebAsync(inValue);
        }
        
        public void TextSpeak() {
            base.Channel.TextSpeak();
        }
        
        public System.Threading.Tasks.Task TextSpeakAsync() {
            return base.Channel.TextSpeakAsync();
        }
    }
}
