//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CT.ADIM.WEB.wsATT_PR_170 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsATT_PR_170.AppToTripWSSoap")]
    public interface AppToTripWSSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/pa_Actualizar_Usuario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable pa_Actualizar_Usuario(string IdUsuario, string Nombres, string Apellidos, string TipoDocumento, string DocumentoUsuario, int Ciudad, string FechaNacimiento, string NumeroCertificado, string VigenciaCertificado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/pa_Actualizar_Usuario", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> pa_Actualizar_UsuarioAsync(string IdUsuario, string Nombres, string Apellidos, string TipoDocumento, string DocumentoUsuario, int Ciudad, string FechaNacimiento, string NumeroCertificado, string VigenciaCertificado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/pa_Consulta_Circuito", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable pa_Consulta_Circuito(string CodIdioma, int fk_usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/pa_Consulta_Circuito", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> pa_Consulta_CircuitoAsync(string CodIdioma, int fk_usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/pa_Consultar_Categorias", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable pa_Consultar_Categorias(string CodIdioma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/pa_Consultar_Categorias", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> pa_Consultar_CategoriasAsync(string CodIdioma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/pa_Consultar_Ciudades", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable pa_Consultar_Ciudades(string CodPais);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/pa_Consultar_Ciudades", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> pa_Consultar_CiudadesAsync(string CodPais);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/pa_Consultar_ImagenSitio", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable pa_Consultar_ImagenSitio(int IdSitio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/pa_Consultar_ImagenSitio", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> pa_Consultar_ImagenSitioAsync(int IdSitio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/pa_Consultar_Paises", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable pa_Consultar_Paises();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/pa_Consultar_Paises", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> pa_Consultar_PaisesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/pa_Consultar_Sitios", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable pa_Consultar_Sitios(string CodIdioma, string IdCircuito);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/pa_Consultar_Sitios", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> pa_Consultar_SitiosAsync(string CodIdioma, string IdCircuito);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/pa_Consultar_TipoId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable pa_Consultar_TipoId();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/pa_Consultar_TipoId", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> pa_Consultar_TipoIdAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/pa_Consultar_Usuario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable pa_Consultar_Usuario(int IdUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/pa_Consultar_Usuario", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> pa_Consultar_UsuarioAsync(int IdUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/pa_Delete_Circuito", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable pa_Delete_Circuito(int id_circuito);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/pa_Delete_Circuito", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> pa_Delete_CircuitoAsync(int id_circuito);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/pa_Delete_Imagenes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable pa_Delete_Imagenes(int id_imagen);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/pa_Delete_Imagenes", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> pa_Delete_ImagenesAsync(int id_imagen);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/pa_Delete_Sitio", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable pa_Delete_Sitio(int Id_Sitio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/pa_Delete_Sitio", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> pa_Delete_SitioAsync(int Id_Sitio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/pa_Insert_Circuito", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string pa_Insert_Circuito(
                    string nombre, 
                    string contexto, 
                    string descripcion_corta, 
                    string descripcion, 
                    string recomendaciones, 
                    string equipamento, 
                    int fk_rango_edad, 
                    string tiempo_estimado, 
                    string codigo_idioma, 
                    int fk_categoria, 
                    int fk_ciudad, 
                    int fk_usuario, 
                    string imagen, 
                    string imagen_img, 
                    int valor, 
                    int otra_moneda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/pa_Insert_Circuito", ReplyAction="*")]
        System.Threading.Tasks.Task<string> pa_Insert_CircuitoAsync(
                    string nombre, 
                    string contexto, 
                    string descripcion_corta, 
                    string descripcion, 
                    string recomendaciones, 
                    string equipamento, 
                    int fk_rango_edad, 
                    string tiempo_estimado, 
                    string codigo_idioma, 
                    int fk_categoria, 
                    int fk_ciudad, 
                    int fk_usuario, 
                    string imagen, 
                    string imagen_img, 
                    int valor, 
                    int otra_moneda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/pa_Insert_ImagenSitio", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable pa_Insert_ImagenSitio(string imagen, string imagen_img, int orden, int fk_sitio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/pa_Insert_ImagenSitio", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> pa_Insert_ImagenSitioAsync(string imagen, string imagen_img, int orden, int fk_sitio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/pa_Insert_Sitio", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string pa_Insert_Sitio(
                    string latitud, 
                    string longitud, 
                    string direccion, 
                    string costo, 
                    string nombre, 
                    string descripcion_corta, 
                    string descripcion, 
                    string equipamento, 
                    string recomendaciones, 
                    string ira, 
                    string codigo_idioma, 
                    string horario, 
                    string tiempo_estimado, 
                    string telefono_sitio, 
                    int fk_circuito, 
                    int orden);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/pa_Insert_Sitio", ReplyAction="*")]
        System.Threading.Tasks.Task<string> pa_Insert_SitioAsync(
                    string latitud, 
                    string longitud, 
                    string direccion, 
                    string costo, 
                    string nombre, 
                    string descripcion_corta, 
                    string descripcion, 
                    string equipamento, 
                    string recomendaciones, 
                    string ira, 
                    string codigo_idioma, 
                    string horario, 
                    string tiempo_estimado, 
                    string telefono_sitio, 
                    int fk_circuito, 
                    int orden);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/pa_Inserta_Usuario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable pa_Inserta_Usuario(string nombres_usuario, string apellido_usuario, string tipo_documento, string documento_usuario, string correo_usuario, string fecha_nacimiento, int ciudad, string clave, string foto_cuenta, int perfil, string numero_certificado, string vigencia_certificado, string foto_certificado, int estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/pa_Inserta_Usuario", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> pa_Inserta_UsuarioAsync(string nombres_usuario, string apellido_usuario, string tipo_documento, string documento_usuario, string correo_usuario, string fecha_nacimiento, int ciudad, string clave, string foto_cuenta, int perfil, string numero_certificado, string vigencia_certificado, string foto_certificado, int estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/pa_Recuperar_Usuario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable pa_Recuperar_Usuario(string Usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/pa_Recuperar_Usuario", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> pa_Recuperar_UsuarioAsync(string Usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/pa_Update_Circuito", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string pa_Update_Circuito(int id_circuito, string nombre, string contexto, string descripcion_corta, string descripcion, string recomendaciones, string equipamento, int fk_rango_edad, string tiempo_estimado, string codigo_idioma, int fk_categoria, string imagen, string imagen_img, int valor, int otra_moneda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/pa_Update_Circuito", ReplyAction="*")]
        System.Threading.Tasks.Task<string> pa_Update_CircuitoAsync(int id_circuito, string nombre, string contexto, string descripcion_corta, string descripcion, string recomendaciones, string equipamento, int fk_rango_edad, string tiempo_estimado, string codigo_idioma, int fk_categoria, string imagen, string imagen_img, int valor, int otra_moneda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/pa_Update_ImagenSitio", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable pa_Update_ImagenSitio(string imagen, int orden, int fk_sitio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/pa_Update_ImagenSitio", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> pa_Update_ImagenSitioAsync(string imagen, int orden, int fk_sitio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/pa_Update_Sitio", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string pa_Update_Sitio(
                    int id_sitio, 
                    string latitud, 
                    string longitud, 
                    string descripcion_corta, 
                    string direccion, 
                    string costo, 
                    string nombre, 
                    string descripcion, 
                    string equipamento, 
                    string recomendaciones, 
                    string ira, 
                    string codigo_idioma, 
                    string horario, 
                    string tiempo_estimado, 
                    string telefono_sitio, 
                    int fk_circuito, 
                    int orden);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/pa_Update_Sitio", ReplyAction="*")]
        System.Threading.Tasks.Task<string> pa_Update_SitioAsync(
                    int id_sitio, 
                    string latitud, 
                    string longitud, 
                    string descripcion_corta, 
                    string direccion, 
                    string costo, 
                    string nombre, 
                    string descripcion, 
                    string equipamento, 
                    string recomendaciones, 
                    string ira, 
                    string codigo_idioma, 
                    string horario, 
                    string tiempo_estimado, 
                    string telefono_sitio, 
                    int fk_circuito, 
                    int orden);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/pa_Send_Mail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string pa_Send_Mail(string Correo, string Asunto, string Mensaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/pa_Send_Mail", ReplyAction="*")]
        System.Threading.Tasks.Task<string> pa_Send_MailAsync(string Correo, string Asunto, string Mensaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/pa_Traducir", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string pa_Traducir(string text, string Entrada, string Salida);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/pa_Traducir", ReplyAction="*")]
        System.Threading.Tasks.Task<string> pa_TraducirAsync(string text, string Entrada, string Salida);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/pa_Insert_Categoriar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string pa_Insert_Categoriar(string nombre_categoria, string codigo_idioma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/pa_Insert_Categoriar", ReplyAction="*")]
        System.Threading.Tasks.Task<string> pa_Insert_CategoriarAsync(string nombre_categoria, string codigo_idioma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/pa_Validacion_Estado", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string pa_Validacion_Estado(int id_usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/pa_Validacion_Estado", ReplyAction="*")]
        System.Threading.Tasks.Task<string> pa_Validacion_EstadoAsync(int id_usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/pa_Insert_Tduracion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string pa_Insert_Tduracion(string tabla, string codigo_idioma, string texto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/pa_Insert_Tduracion", ReplyAction="*")]
        System.Threading.Tasks.Task<string> pa_Insert_TduracionAsync(string tabla, string codigo_idioma, string texto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/pa_Consulta_Generica", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable pa_Consulta_Generica(string tabla, string codigo_idioma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/pa_Consulta_Generica", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> pa_Consulta_GenericaAsync(string tabla, string codigo_idioma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/pa_Consulta_Generica_Moneda", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable pa_Consulta_Generica_Moneda(string tabla);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/pa_Consulta_Generica_Moneda", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> pa_Consulta_Generica_MonedaAsync(string tabla);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/pa_Update_Imagen_Circuito", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable pa_Update_Imagen_Circuito(string imagen, string imagen_img, int id_circuito);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/pa_Update_Imagen_Circuito", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> pa_Update_Imagen_CircuitoAsync(string imagen, string imagen_img, int id_circuito);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/pa_Update_Circuito_2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string pa_Update_Circuito_2(int fk_categoria, int valor, int otra_moneda, int fk_rango_edad, int id_circuito, string nombre, string contexto, string descripcion_corta, string descripcion, string recomendaciones, string equipamento, string tiempo_estimado, string codigo_idioma, string imagen, string imagen_img);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/pa_Update_Circuito_2", ReplyAction="*")]
        System.Threading.Tasks.Task<string> pa_Update_Circuito_2Async(int fk_categoria, int valor, int otra_moneda, int fk_rango_edad, int id_circuito, string nombre, string contexto, string descripcion_corta, string descripcion, string recomendaciones, string equipamento, string tiempo_estimado, string codigo_idioma, string imagen, string imagen_img);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/pa_Update_Sitio_2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string pa_Update_Sitio_2(
                    int fk_circuito, 
                    int orden, 
                    int id_sitio, 
                    string latitud, 
                    string longitud, 
                    string direccion, 
                    string costo, 
                    string nombre, 
                    string descripcion_corta, 
                    string descripcion, 
                    string equipamento, 
                    string recomendaciones, 
                    string ira, 
                    string codigo_idioma, 
                    string horario, 
                    string tiempo_estimado, 
                    string telefono_sitio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/pa_Update_Sitio_2", ReplyAction="*")]
        System.Threading.Tasks.Task<string> pa_Update_Sitio_2Async(
                    int fk_circuito, 
                    int orden, 
                    int id_sitio, 
                    string latitud, 
                    string longitud, 
                    string direccion, 
                    string costo, 
                    string nombre, 
                    string descripcion_corta, 
                    string descripcion, 
                    string equipamento, 
                    string recomendaciones, 
                    string ira, 
                    string codigo_idioma, 
                    string horario, 
                    string tiempo_estimado, 
                    string telefono_sitio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GeneraStream", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GeneraStream(string tabla, string clave, string campo, string cadena, string codigo_idioma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GeneraStream", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GeneraStreamAsync(string tabla, string clave, string campo, string cadena, string codigo_idioma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/pa_Actualiza_General", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string pa_Actualiza_General(string tabla, string clave, string campo, string valor, string codigo_idioma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/pa_Actualiza_General", ReplyAction="*")]
        System.Threading.Tasks.Task<string> pa_Actualiza_GeneralAsync(string tabla, string clave, string campo, string valor, string codigo_idioma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/pa_Insert_General", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string pa_Insert_General(string tabla, string clave, string campo, string valor, string codigo_idioma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/pa_Insert_General", ReplyAction="*")]
        System.Threading.Tasks.Task<string> pa_Insert_GeneralAsync(string tabla, string clave, string campo, string valor, string codigo_idioma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/generastream_programado", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string generastream_programado(string tabla);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/generastream_programado", ReplyAction="*")]
        System.Threading.Tasks.Task<string> generastream_programadoAsync(string tabla);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/validar_traduce", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string validar_traduce();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/validar_traduce", ReplyAction="*")]
        System.Threading.Tasks.Task<string> validar_traduceAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/validar_stream", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string validar_stream();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/validar_stream", ReplyAction="*")]
        System.Threading.Tasks.Task<string> validar_streamAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/pa_Consultar_audios", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable pa_Consultar_audios(int fk_circuito, string codigo_idioma);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/pa_Consultar_audios", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> pa_Consultar_audiosAsync(int fk_circuito, string codigo_idioma);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AppToTripWSSoapChannel : CT.ADIM.WEB.wsATT_PR_170.AppToTripWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AppToTripWSSoapClient : System.ServiceModel.ClientBase<CT.ADIM.WEB.wsATT_PR_170.AppToTripWSSoap>, CT.ADIM.WEB.wsATT_PR_170.AppToTripWSSoap {
        
        public AppToTripWSSoapClient() {
        }
        
        public AppToTripWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AppToTripWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AppToTripWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AppToTripWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable pa_Actualizar_Usuario(string IdUsuario, string Nombres, string Apellidos, string TipoDocumento, string DocumentoUsuario, int Ciudad, string FechaNacimiento, string NumeroCertificado, string VigenciaCertificado) {
            return base.Channel.pa_Actualizar_Usuario(IdUsuario, Nombres, Apellidos, TipoDocumento, DocumentoUsuario, Ciudad, FechaNacimiento, NumeroCertificado, VigenciaCertificado);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> pa_Actualizar_UsuarioAsync(string IdUsuario, string Nombres, string Apellidos, string TipoDocumento, string DocumentoUsuario, int Ciudad, string FechaNacimiento, string NumeroCertificado, string VigenciaCertificado) {
            return base.Channel.pa_Actualizar_UsuarioAsync(IdUsuario, Nombres, Apellidos, TipoDocumento, DocumentoUsuario, Ciudad, FechaNacimiento, NumeroCertificado, VigenciaCertificado);
        }
        
        public System.Data.DataTable pa_Consulta_Circuito(string CodIdioma, int fk_usuario) {
            return base.Channel.pa_Consulta_Circuito(CodIdioma, fk_usuario);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> pa_Consulta_CircuitoAsync(string CodIdioma, int fk_usuario) {
            return base.Channel.pa_Consulta_CircuitoAsync(CodIdioma, fk_usuario);
        }
        
        public System.Data.DataTable pa_Consultar_Categorias(string CodIdioma) {
            return base.Channel.pa_Consultar_Categorias(CodIdioma);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> pa_Consultar_CategoriasAsync(string CodIdioma) {
            return base.Channel.pa_Consultar_CategoriasAsync(CodIdioma);
        }
        
        public System.Data.DataTable pa_Consultar_Ciudades(string CodPais) {
            return base.Channel.pa_Consultar_Ciudades(CodPais);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> pa_Consultar_CiudadesAsync(string CodPais) {
            return base.Channel.pa_Consultar_CiudadesAsync(CodPais);
        }
        
        public System.Data.DataTable pa_Consultar_ImagenSitio(int IdSitio) {
            return base.Channel.pa_Consultar_ImagenSitio(IdSitio);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> pa_Consultar_ImagenSitioAsync(int IdSitio) {
            return base.Channel.pa_Consultar_ImagenSitioAsync(IdSitio);
        }
        
        public System.Data.DataTable pa_Consultar_Paises() {
            return base.Channel.pa_Consultar_Paises();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> pa_Consultar_PaisesAsync() {
            return base.Channel.pa_Consultar_PaisesAsync();
        }
        
        public System.Data.DataTable pa_Consultar_Sitios(string CodIdioma, string IdCircuito) {
            return base.Channel.pa_Consultar_Sitios(CodIdioma, IdCircuito);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> pa_Consultar_SitiosAsync(string CodIdioma, string IdCircuito) {
            return base.Channel.pa_Consultar_SitiosAsync(CodIdioma, IdCircuito);
        }
        
        public System.Data.DataTable pa_Consultar_TipoId() {
            return base.Channel.pa_Consultar_TipoId();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> pa_Consultar_TipoIdAsync() {
            return base.Channel.pa_Consultar_TipoIdAsync();
        }
        
        public System.Data.DataTable pa_Consultar_Usuario(int IdUsuario) {
            return base.Channel.pa_Consultar_Usuario(IdUsuario);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> pa_Consultar_UsuarioAsync(int IdUsuario) {
            return base.Channel.pa_Consultar_UsuarioAsync(IdUsuario);
        }
        
        public System.Data.DataTable pa_Delete_Circuito(int id_circuito) {
            return base.Channel.pa_Delete_Circuito(id_circuito);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> pa_Delete_CircuitoAsync(int id_circuito) {
            return base.Channel.pa_Delete_CircuitoAsync(id_circuito);
        }
        
        public System.Data.DataTable pa_Delete_Imagenes(int id_imagen) {
            return base.Channel.pa_Delete_Imagenes(id_imagen);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> pa_Delete_ImagenesAsync(int id_imagen) {
            return base.Channel.pa_Delete_ImagenesAsync(id_imagen);
        }
        
        public System.Data.DataTable pa_Delete_Sitio(int Id_Sitio) {
            return base.Channel.pa_Delete_Sitio(Id_Sitio);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> pa_Delete_SitioAsync(int Id_Sitio) {
            return base.Channel.pa_Delete_SitioAsync(Id_Sitio);
        }
        
        public string pa_Insert_Circuito(
                    string nombre, 
                    string contexto, 
                    string descripcion_corta, 
                    string descripcion, 
                    string recomendaciones, 
                    string equipamento, 
                    int fk_rango_edad, 
                    string tiempo_estimado, 
                    string codigo_idioma, 
                    int fk_categoria, 
                    int fk_ciudad, 
                    int fk_usuario, 
                    string imagen, 
                    string imagen_img, 
                    int valor, 
                    int otra_moneda) {
            return base.Channel.pa_Insert_Circuito(nombre, contexto, descripcion_corta, descripcion, recomendaciones, equipamento, fk_rango_edad, tiempo_estimado, codigo_idioma, fk_categoria, fk_ciudad, fk_usuario, imagen, imagen_img, valor, otra_moneda);
        }
        
        public System.Threading.Tasks.Task<string> pa_Insert_CircuitoAsync(
                    string nombre, 
                    string contexto, 
                    string descripcion_corta, 
                    string descripcion, 
                    string recomendaciones, 
                    string equipamento, 
                    int fk_rango_edad, 
                    string tiempo_estimado, 
                    string codigo_idioma, 
                    int fk_categoria, 
                    int fk_ciudad, 
                    int fk_usuario, 
                    string imagen, 
                    string imagen_img, 
                    int valor, 
                    int otra_moneda) {
            return base.Channel.pa_Insert_CircuitoAsync(nombre, contexto, descripcion_corta, descripcion, recomendaciones, equipamento, fk_rango_edad, tiempo_estimado, codigo_idioma, fk_categoria, fk_ciudad, fk_usuario, imagen, imagen_img, valor, otra_moneda);
        }
        
        public System.Data.DataTable pa_Insert_ImagenSitio(string imagen, string imagen_img, int orden, int fk_sitio) {
            return base.Channel.pa_Insert_ImagenSitio(imagen, imagen_img, orden, fk_sitio);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> pa_Insert_ImagenSitioAsync(string imagen, string imagen_img, int orden, int fk_sitio) {
            return base.Channel.pa_Insert_ImagenSitioAsync(imagen, imagen_img, orden, fk_sitio);
        }
        
        public string pa_Insert_Sitio(
                    string latitud, 
                    string longitud, 
                    string direccion, 
                    string costo, 
                    string nombre, 
                    string descripcion_corta, 
                    string descripcion, 
                    string equipamento, 
                    string recomendaciones, 
                    string ira, 
                    string codigo_idioma, 
                    string horario, 
                    string tiempo_estimado, 
                    string telefono_sitio, 
                    int fk_circuito, 
                    int orden) {
            return base.Channel.pa_Insert_Sitio(latitud, longitud, direccion, costo, nombre, descripcion_corta, descripcion, equipamento, recomendaciones, ira, codigo_idioma, horario, tiempo_estimado, telefono_sitio, fk_circuito, orden);
        }
        
        public System.Threading.Tasks.Task<string> pa_Insert_SitioAsync(
                    string latitud, 
                    string longitud, 
                    string direccion, 
                    string costo, 
                    string nombre, 
                    string descripcion_corta, 
                    string descripcion, 
                    string equipamento, 
                    string recomendaciones, 
                    string ira, 
                    string codigo_idioma, 
                    string horario, 
                    string tiempo_estimado, 
                    string telefono_sitio, 
                    int fk_circuito, 
                    int orden) {
            return base.Channel.pa_Insert_SitioAsync(latitud, longitud, direccion, costo, nombre, descripcion_corta, descripcion, equipamento, recomendaciones, ira, codigo_idioma, horario, tiempo_estimado, telefono_sitio, fk_circuito, orden);
        }
        
        public System.Data.DataTable pa_Inserta_Usuario(string nombres_usuario, string apellido_usuario, string tipo_documento, string documento_usuario, string correo_usuario, string fecha_nacimiento, int ciudad, string clave, string foto_cuenta, int perfil, string numero_certificado, string vigencia_certificado, string foto_certificado, int estado) {
            return base.Channel.pa_Inserta_Usuario(nombres_usuario, apellido_usuario, tipo_documento, documento_usuario, correo_usuario, fecha_nacimiento, ciudad, clave, foto_cuenta, perfil, numero_certificado, vigencia_certificado, foto_certificado, estado);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> pa_Inserta_UsuarioAsync(string nombres_usuario, string apellido_usuario, string tipo_documento, string documento_usuario, string correo_usuario, string fecha_nacimiento, int ciudad, string clave, string foto_cuenta, int perfil, string numero_certificado, string vigencia_certificado, string foto_certificado, int estado) {
            return base.Channel.pa_Inserta_UsuarioAsync(nombres_usuario, apellido_usuario, tipo_documento, documento_usuario, correo_usuario, fecha_nacimiento, ciudad, clave, foto_cuenta, perfil, numero_certificado, vigencia_certificado, foto_certificado, estado);
        }
        
        public System.Data.DataTable pa_Recuperar_Usuario(string Usuario) {
            return base.Channel.pa_Recuperar_Usuario(Usuario);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> pa_Recuperar_UsuarioAsync(string Usuario) {
            return base.Channel.pa_Recuperar_UsuarioAsync(Usuario);
        }
        
        public string pa_Update_Circuito(int id_circuito, string nombre, string contexto, string descripcion_corta, string descripcion, string recomendaciones, string equipamento, int fk_rango_edad, string tiempo_estimado, string codigo_idioma, int fk_categoria, string imagen, string imagen_img, int valor, int otra_moneda) {
            return base.Channel.pa_Update_Circuito(id_circuito, nombre, contexto, descripcion_corta, descripcion, recomendaciones, equipamento, fk_rango_edad, tiempo_estimado, codigo_idioma, fk_categoria, imagen, imagen_img, valor, otra_moneda);
        }
        
        public System.Threading.Tasks.Task<string> pa_Update_CircuitoAsync(int id_circuito, string nombre, string contexto, string descripcion_corta, string descripcion, string recomendaciones, string equipamento, int fk_rango_edad, string tiempo_estimado, string codigo_idioma, int fk_categoria, string imagen, string imagen_img, int valor, int otra_moneda) {
            return base.Channel.pa_Update_CircuitoAsync(id_circuito, nombre, contexto, descripcion_corta, descripcion, recomendaciones, equipamento, fk_rango_edad, tiempo_estimado, codigo_idioma, fk_categoria, imagen, imagen_img, valor, otra_moneda);
        }
        
        public System.Data.DataTable pa_Update_ImagenSitio(string imagen, int orden, int fk_sitio) {
            return base.Channel.pa_Update_ImagenSitio(imagen, orden, fk_sitio);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> pa_Update_ImagenSitioAsync(string imagen, int orden, int fk_sitio) {
            return base.Channel.pa_Update_ImagenSitioAsync(imagen, orden, fk_sitio);
        }
        
        public string pa_Update_Sitio(
                    int id_sitio, 
                    string latitud, 
                    string longitud, 
                    string descripcion_corta, 
                    string direccion, 
                    string costo, 
                    string nombre, 
                    string descripcion, 
                    string equipamento, 
                    string recomendaciones, 
                    string ira, 
                    string codigo_idioma, 
                    string horario, 
                    string tiempo_estimado, 
                    string telefono_sitio, 
                    int fk_circuito, 
                    int orden) {
            return base.Channel.pa_Update_Sitio(id_sitio, latitud, longitud, descripcion_corta, direccion, costo, nombre, descripcion, equipamento, recomendaciones, ira, codigo_idioma, horario, tiempo_estimado, telefono_sitio, fk_circuito, orden);
        }
        
        public System.Threading.Tasks.Task<string> pa_Update_SitioAsync(
                    int id_sitio, 
                    string latitud, 
                    string longitud, 
                    string descripcion_corta, 
                    string direccion, 
                    string costo, 
                    string nombre, 
                    string descripcion, 
                    string equipamento, 
                    string recomendaciones, 
                    string ira, 
                    string codigo_idioma, 
                    string horario, 
                    string tiempo_estimado, 
                    string telefono_sitio, 
                    int fk_circuito, 
                    int orden) {
            return base.Channel.pa_Update_SitioAsync(id_sitio, latitud, longitud, descripcion_corta, direccion, costo, nombre, descripcion, equipamento, recomendaciones, ira, codigo_idioma, horario, tiempo_estimado, telefono_sitio, fk_circuito, orden);
        }
        
        public string pa_Send_Mail(string Correo, string Asunto, string Mensaje) {
            return base.Channel.pa_Send_Mail(Correo, Asunto, Mensaje);
        }
        
        public System.Threading.Tasks.Task<string> pa_Send_MailAsync(string Correo, string Asunto, string Mensaje) {
            return base.Channel.pa_Send_MailAsync(Correo, Asunto, Mensaje);
        }
        
        public string pa_Traducir(string text, string Entrada, string Salida) {
            return base.Channel.pa_Traducir(text, Entrada, Salida);
        }
        
        public System.Threading.Tasks.Task<string> pa_TraducirAsync(string text, string Entrada, string Salida) {
            return base.Channel.pa_TraducirAsync(text, Entrada, Salida);
        }
        
        public string pa_Insert_Categoriar(string nombre_categoria, string codigo_idioma) {
            return base.Channel.pa_Insert_Categoriar(nombre_categoria, codigo_idioma);
        }
        
        public System.Threading.Tasks.Task<string> pa_Insert_CategoriarAsync(string nombre_categoria, string codigo_idioma) {
            return base.Channel.pa_Insert_CategoriarAsync(nombre_categoria, codigo_idioma);
        }
        
        public string pa_Validacion_Estado(int id_usuario) {
            return base.Channel.pa_Validacion_Estado(id_usuario);
        }
        
        public System.Threading.Tasks.Task<string> pa_Validacion_EstadoAsync(int id_usuario) {
            return base.Channel.pa_Validacion_EstadoAsync(id_usuario);
        }
        
        public string pa_Insert_Tduracion(string tabla, string codigo_idioma, string texto) {
            return base.Channel.pa_Insert_Tduracion(tabla, codigo_idioma, texto);
        }
        
        public System.Threading.Tasks.Task<string> pa_Insert_TduracionAsync(string tabla, string codigo_idioma, string texto) {
            return base.Channel.pa_Insert_TduracionAsync(tabla, codigo_idioma, texto);
        }
        
        public System.Data.DataTable pa_Consulta_Generica(string tabla, string codigo_idioma) {
            return base.Channel.pa_Consulta_Generica(tabla, codigo_idioma);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> pa_Consulta_GenericaAsync(string tabla, string codigo_idioma) {
            return base.Channel.pa_Consulta_GenericaAsync(tabla, codigo_idioma);
        }
        
        public System.Data.DataTable pa_Consulta_Generica_Moneda(string tabla) {
            return base.Channel.pa_Consulta_Generica_Moneda(tabla);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> pa_Consulta_Generica_MonedaAsync(string tabla) {
            return base.Channel.pa_Consulta_Generica_MonedaAsync(tabla);
        }
        
        public System.Data.DataTable pa_Update_Imagen_Circuito(string imagen, string imagen_img, int id_circuito) {
            return base.Channel.pa_Update_Imagen_Circuito(imagen, imagen_img, id_circuito);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> pa_Update_Imagen_CircuitoAsync(string imagen, string imagen_img, int id_circuito) {
            return base.Channel.pa_Update_Imagen_CircuitoAsync(imagen, imagen_img, id_circuito);
        }
        
        public string pa_Update_Circuito_2(int fk_categoria, int valor, int otra_moneda, int fk_rango_edad, int id_circuito, string nombre, string contexto, string descripcion_corta, string descripcion, string recomendaciones, string equipamento, string tiempo_estimado, string codigo_idioma, string imagen, string imagen_img) {
            return base.Channel.pa_Update_Circuito_2(fk_categoria, valor, otra_moneda, fk_rango_edad, id_circuito, nombre, contexto, descripcion_corta, descripcion, recomendaciones, equipamento, tiempo_estimado, codigo_idioma, imagen, imagen_img);
        }
        
        public System.Threading.Tasks.Task<string> pa_Update_Circuito_2Async(int fk_categoria, int valor, int otra_moneda, int fk_rango_edad, int id_circuito, string nombre, string contexto, string descripcion_corta, string descripcion, string recomendaciones, string equipamento, string tiempo_estimado, string codigo_idioma, string imagen, string imagen_img) {
            return base.Channel.pa_Update_Circuito_2Async(fk_categoria, valor, otra_moneda, fk_rango_edad, id_circuito, nombre, contexto, descripcion_corta, descripcion, recomendaciones, equipamento, tiempo_estimado, codigo_idioma, imagen, imagen_img);
        }
        
        public string pa_Update_Sitio_2(
                    int fk_circuito, 
                    int orden, 
                    int id_sitio, 
                    string latitud, 
                    string longitud, 
                    string direccion, 
                    string costo, 
                    string nombre, 
                    string descripcion_corta, 
                    string descripcion, 
                    string equipamento, 
                    string recomendaciones, 
                    string ira, 
                    string codigo_idioma, 
                    string horario, 
                    string tiempo_estimado, 
                    string telefono_sitio) {
            return base.Channel.pa_Update_Sitio_2(fk_circuito, orden, id_sitio, latitud, longitud, direccion, costo, nombre, descripcion_corta, descripcion, equipamento, recomendaciones, ira, codigo_idioma, horario, tiempo_estimado, telefono_sitio);
        }
        
        public System.Threading.Tasks.Task<string> pa_Update_Sitio_2Async(
                    int fk_circuito, 
                    int orden, 
                    int id_sitio, 
                    string latitud, 
                    string longitud, 
                    string direccion, 
                    string costo, 
                    string nombre, 
                    string descripcion_corta, 
                    string descripcion, 
                    string equipamento, 
                    string recomendaciones, 
                    string ira, 
                    string codigo_idioma, 
                    string horario, 
                    string tiempo_estimado, 
                    string telefono_sitio) {
            return base.Channel.pa_Update_Sitio_2Async(fk_circuito, orden, id_sitio, latitud, longitud, direccion, costo, nombre, descripcion_corta, descripcion, equipamento, recomendaciones, ira, codigo_idioma, horario, tiempo_estimado, telefono_sitio);
        }
        
        public string GeneraStream(string tabla, string clave, string campo, string cadena, string codigo_idioma) {
            return base.Channel.GeneraStream(tabla, clave, campo, cadena, codigo_idioma);
        }
        
        public System.Threading.Tasks.Task<string> GeneraStreamAsync(string tabla, string clave, string campo, string cadena, string codigo_idioma) {
            return base.Channel.GeneraStreamAsync(tabla, clave, campo, cadena, codigo_idioma);
        }
        
        public string pa_Actualiza_General(string tabla, string clave, string campo, string valor, string codigo_idioma) {
            return base.Channel.pa_Actualiza_General(tabla, clave, campo, valor, codigo_idioma);
        }
        
        public System.Threading.Tasks.Task<string> pa_Actualiza_GeneralAsync(string tabla, string clave, string campo, string valor, string codigo_idioma) {
            return base.Channel.pa_Actualiza_GeneralAsync(tabla, clave, campo, valor, codigo_idioma);
        }
        
        public string pa_Insert_General(string tabla, string clave, string campo, string valor, string codigo_idioma) {
            return base.Channel.pa_Insert_General(tabla, clave, campo, valor, codigo_idioma);
        }
        
        public System.Threading.Tasks.Task<string> pa_Insert_GeneralAsync(string tabla, string clave, string campo, string valor, string codigo_idioma) {
            return base.Channel.pa_Insert_GeneralAsync(tabla, clave, campo, valor, codigo_idioma);
        }
        
        public string generastream_programado(string tabla) {
            return base.Channel.generastream_programado(tabla);
        }
        
        public System.Threading.Tasks.Task<string> generastream_programadoAsync(string tabla) {
            return base.Channel.generastream_programadoAsync(tabla);
        }
        
        public string validar_traduce() {
            return base.Channel.validar_traduce();
        }
        
        public System.Threading.Tasks.Task<string> validar_traduceAsync() {
            return base.Channel.validar_traduceAsync();
        }
        
        public string validar_stream() {
            return base.Channel.validar_stream();
        }
        
        public System.Threading.Tasks.Task<string> validar_streamAsync() {
            return base.Channel.validar_streamAsync();
        }
        
        public System.Data.DataTable pa_Consultar_audios(int fk_circuito, string codigo_idioma) {
            return base.Channel.pa_Consultar_audios(fk_circuito, codigo_idioma);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> pa_Consultar_audiosAsync(int fk_circuito, string codigo_idioma) {
            return base.Channel.pa_Consultar_audiosAsync(fk_circuito, codigo_idioma);
        }
    }
}
